=== paths-erc/coptic-texts/paths-schema.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified" targetNamespace="http://www.tei-c.org/ns/1.0" xmlns:ns1="http://www.tei-c.org/ns/1.0">

  <xs:element name="TEI">

    <xs:complexType>
      <xs:sequence>
        <xs:element ref="ns1:teiHeader"/>
        <xs:element ref="ns1:text"/>
      </xs:sequence>
    </xs:complexType>

  </xs:element>

  <xs:element name="teiHeader">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="ns1:fileDesc"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="fileDesc">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="ns1:titleStmt"/>
        <xs:element ref="ns1:publicationStmt"/>
        <xs:element ref="ns1:sourceDesc"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="titleStmt">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="ns1:title"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="title" type="xs:string"/>
  <xs:element name="publicationStmt">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="ns1:p"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="sourceDesc">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="ns1:p"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="text">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="ns1:body"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="body">
    <xs:complexType>
      <xs:sequence>
        <xs:element maxOccurs="unbounded" ref="ns1:p"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>

  <xs:element name="p">
    <xs:complexType mixed="true">
      <xs:choice minOccurs="0" maxOccurs="unbounded">
        <xs:element ref="ns1:date"/>
        <xs:element ref="ns1:gap"/>
        <xs:element ref="ns1:lb"/>
        <xs:element ref="ns1:persName"/>
        <xs:element ref="ns1:placeName"/>
        <xs:element ref="ns1:roleName"/>
        <xs:element ref="ns1:quote"/>
        <xs:element ref="ns1:org"/>
        <xs:element ref="ns1:rs"/>
      </xs:choice>
      <xs:attribute name="n" type="xs:integer" use="optional" />
    </xs:complexType>
  </xs:element>

  <xs:element name="date">
    <xs:complexType mixed="true">
      <xs:choice minOccurs="0" maxOccurs="unbounded">
        <xs:element ref="ns1:lb"/>
      </xs:choice>
      <xs:attribute name="type" use="required">
        <xs:simpleType>
          <xs:restriction base="xs:string">
            <xs:enumeration value="commemoration" />
            <xs:enumeration value="official_feast" />
            <xs:enumeration value="concilia" />
            <xs:enumeration value="liturgies_ceremonies" />
          </xs:restriction>
        </xs:simpleType>
      </xs:attribute>
    </xs:complexType>
  </xs:element>

  <xs:element name="gap">
    <xs:complexType/>
  </xs:element>
  <xs:element name="lb">
    <xs:complexType/>
  </xs:element>

  <xs:element name="persName">
    <xs:complexType mixed="true">
      <xs:choice minOccurs="0" maxOccurs="unbounded">
        <xs:element ref="ns1:lb"/>
        <xs:element ref="ns1:roleName"/>
      </xs:choice>
      <xs:attribute name="ref" use="optional" />
      <xs:attribute name="type" use="required">
        <xs:simpleType>
          <xs:restriction base="xs:string">
            <xs:enumeration value="saint" />
            <xs:enumeration value="martyr" />
            <xs:enumeration value="apostle" />
            <xs:enumeration value="bishop" />
            <xs:enumeration value="archi_bishop" />
            <xs:enumeration value="monk" />

            <xs:enumeration value="arch_angel" />
            <xs:enumeration value="daemon" />

            <xs:enumeration value="emperor_king" />
            <xs:enumeration value="civil" />
            <xs:enumeration value="military" />
            <xs:enumeration value="ecclesiastical" />
            <xs:enumeration value="biblical" />
            <xs:enumeration value="pagan_deity" />

            <xs:enumeration value="donor" />
            <xs:enumeration value="copyist" />
            <xs:enumeration value="restorer" />
          </xs:restriction>
        </xs:simpleType>
      </xs:attribute>
    </xs:complexType>
  </xs:element>


  <xs:element name="placeName">
    <xs:complexType mixed="true">
   	  <xs:choice minOccurs="0" maxOccurs="unbounded">
        <xs:element ref="ns1:persName"/>
        <xs:element ref="ns1:lb"/>
      </xs:choice>
      <xs:attribute name="ref" use="optional" />
      <xs:attribute name="subtype" use="optional">
        <xs:simpleType>
          <xs:restriction base="xs:string">
            <!-- Admin places -->
            <xs:enumeration value="egyptian" />
            <xs:enumeration value="non_egyptian" />
          </xs:restriction>
        </xs:simpleType>
      </xs:attribute>
      <xs:attribute name="type" use="required">
        <xs:simpleType>
          <xs:restriction base="xs:string">
            <!-- Admin places -->
            <xs:enumeration value="country" />
            <xs:enumeration value="region" />
            <xs:enumeration value="district_nomos" />
            <xs:enumeration value="city_village" />
            <xs:enumeration value="topos_ma" />
            <!-- Religios places -->
            <xs:enumeration value="monastery" />
            <xs:enumeration value="church_basilica" />
            <xs:enumeration value="episkopeion" />
            <xs:enumeration value="chapel" />
            <xs:enumeration value="oratory" />
            <xs:enumeration value="martyr_shrine" />
            <xs:enumeration value="temple" />
            <xs:enumeration value="hermitage" />
            <xs:enumeration value="tomb" />
            <!-- Natural fetures -->
            <xs:enumeration value="mount" />
            <xs:enumeration value="river" />
            <xs:enumeration value="lake" />
            <xs:enumeration value="harbour" />
            <!-- Lit -->
            <xs:enumeration value="biblical" />
          </xs:restriction>
        </xs:simpleType>
      </xs:attribute>
    </xs:complexType>
  </xs:element>

  <xs:element name="roleName">
    <xs:complexType mixed="true">
      <xs:choice minOccurs="0" maxOccurs="unbounded">
        <xs:element ref="ns1:lb"/>
      </xs:choice>
      <xs:attribute name="ref" use="optional" />
      <xs:attribute name="type" use="required">
        <xs:simpleType>
          <xs:restriction base="xs:string">
            <xs:enumeration value="religious" />
            <xs:enumeration value="ecclesiastical" />
            <xs:enumeration value="civil" />
            <xs:enumeration value="military" />
          </xs:restriction>
        </xs:simpleType>
      </xs:attribute>
    </xs:complexType>
  </xs:element>

  <xs:element name="org">
    <xs:complexType mixed="true">
      <xs:choice minOccurs="0" maxOccurs="unbounded">
        <xs:element ref="ns1:lb"/>
      </xs:choice>
      <xs:attribute name="ref" use="optional" />
      <xs:attribute name="type" use="required">
        <xs:simpleType>
          <xs:restriction base="xs:string">
            <xs:enumeration value="religious" />
            <xs:enumeration value="ethnic" />
          </xs:restriction>
        </xs:simpleType>
      </xs:attribute>
    </xs:complexType>
  </xs:element>

  <xs:element name="quote">
    <xs:complexType mixed="true">
      <xs:choice minOccurs="0" maxOccurs="unbounded">
      	<xs:element ref="ns1:date"/>
        <xs:element ref="ns1:gap"/>
        <xs:element ref="ns1:lb"/>
        <xs:element ref="ns1:persName"/>
        <xs:element ref="ns1:placeName"/>
        <xs:element ref="ns1:roleName"/>
        <xs:element ref="ns1:org"/>
        <xs:element ref="ns1:rs"/>
      </xs:choice>
      <xs:attribute name="ref" use="optional" />
      <xs:attribute name="type" use="required">
        <xs:simpleType>
          <xs:restriction base="xs:string">
            <xs:enumeration value="biblical" />
            <xs:enumeration value="classical" />
          </xs:restriction>
        </xs:simpleType>
      </xs:attribute>
    </xs:complexType>
  </xs:element>

  <xs:element name="rs">
    <xs:complexType mixed="true">
      <xs:choice minOccurs="0" maxOccurs="unbounded">
        <xs:element ref="ns1:lb"/>
      </xs:choice>
      <xs:attribute name="ref" use="optional" />
      <xs:attribute name="type" use="required">
        <xs:simpleType>
          <xs:restriction base="xs:string">
            <xs:enumeration value="object" />
            <xs:enumeration value="furniture" />
            <xs:enumeration value="service" />
          </xs:restriction>
        </xs:simpleType>
      </xs:attribute>
    </xs:complexType>
  </xs:element>

</xs:schema>

=== paths-erc/coptic-texts/colophons/paths.colophons.25.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-model href="http://www.tei-c.org/release/xml/tei/custom/schema/relaxng/tei_ms.rng" type="application/xml"
schematypens="http://purl.oclc.org/dsdl/schematron"?>
<TEI xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="http://www.tei-c.org/ns/1.0 ../paths-schema.xsd"
  xmlns="http://www.tei-c.org/ns/1.0">
  <teiHeader>
    <fileDesc>
      <titleStmt>
        <title>paths.colophons.25</title>
      </titleStmt>
      <publicationStmt>
        <p>paths.colophons.25</p>
      </publicationStmt>
      <sourceDesc>
        <p>paths.colophons.25</p>
      </sourceDesc>
    </fileDesc>
  </teiHeader>
  <text>
    <body>
      <p>
ⲡ⳪︦ ⲓ(ⲏⲥⲟⲩ)ⲥ ⲡⲉⲭ(ⲣⲓⲥⲧⲟ)ⲥ ⲥⲙⲟⲩ ⲡⲙⲁⲓⲛⲟⲩϯ ⲛⲥⲁⲛ | ⲛⲧⲁⲃⲃⲓⲡⲣⲁⲩ ⲛⲡⲓⲕⲉⲫⲁⲗⲁⲓⲟⲛ ϫⲟⲙⲉ | ⲁⲃⲧⲁϥ ⲉϩⲟⲩⲛ ⲉ<placeName type="monastery" ref="paths:places:99">ⲡⲁⲣⲭⲁⲛⲅⲉⲗⲟⲥ ⲙⲓⲭⲁⲏⲗ</placeName> | ϩⲁⲡⲟⲩϫⲁⲓ ⲛⲧⲉϥⲡⲯⲏⲭⲏ ϫⲉⲕⲁⲥ ⲉⲣⲉⲡ<persName type="arch_angel">ⲁⲣ|(5)ⲭⲁⲅⲅⲉⲗⲟⲥ ⲙⲓⲭⲁⲏⲗ</persName> ϫⲓⲡⲉϩⲙⲁⲧ ⲉⲡⲛⲟⲩϯ | ϫⲟⲃ ⲉⲃⲕⲟ ⲛⲁⲃ ⲉⲃⲁⲗ ⲉⲛⲉϥⲛⲁⲃⲓ ⲛⲧⲁⲃⲁⲩ | ⲁⲩⲱ ⲉϥϣⲁⲛⲓ ⲉⲃⲁⲗ ϩⲉⲥⲟⲙⲁ ⲧⲉⲃⲉⲙⲡϣⲁ ⲛ|ⲥⲟⲇⲉⲙ ⲉⲧⲉⲥⲙⲏ ⲙⲙⲁⲕⲁⲣⲓ ⲉⲧⲉⲙⲙⲁⲩ ϫⲉⲁⲙⲟⲩ | ⲡⲉⲧⲥⲙⲁⲙⲁⲧ ⲛⲧⲉⲡⲁⲓⲱⲧ ⲁⲗⲓⲕⲗⲉⲣⲟ̣ⲙⲓⲁ | (10) ⲛⲧⲙⲉⲧⲉⲣⲁ ⲛⲧⲁⲩⲥⲉⲃⲧⲟⲥ ⲛⲉⲧⲉⲛ ⲉϫⲓⲛⲕⲁ|ⲧⲁⲃⲟⲗⲏ ⲛⲕⲟⲥⲙⲟⲥ ϩⲁⲙⲏⲛ ⲉⲥⲉϣⲟⲡⲓ | ⲇⲓⲟⲕⲗⲏϯⲓⲁⲛⲟⲩ⸱ⲭ︦ⲕ︦ⲃ︦⸱
    </p>
    </body>
  </text>
</TEI>

=== paths-erc/coptic-texts/colophons/paths.colophons.14.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-model href="http://www.tei-c.org/release/xml/tei/custom/schema/relaxng/tei_ms.rng" type="application/xml"
schematypens="http://purl.oclc.org/dsdl/schematron"?>
<TEI xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="http://www.tei-c.org/ns/1.0 ../paths-schema.xsd"
  xmlns="http://www.tei-c.org/ns/1.0">
  <teiHeader>
    <fileDesc>
      <titleStmt>
        <title>paths.colophons.14</title>
      </titleStmt>
      <publicationStmt>
        <p>paths.colophons.14</p>
      </publicationStmt>
      <sourceDesc>
        <p>paths.colophons.14</p>
      </sourceDesc>
    </fileDesc>
  </teiHeader>
  <text>
    <body>
      <p>
⳨ ⲥⲩⲛ ⲑ(ⲉⲱⲓ) ⲛⲁⲉⲓⲟⲧⲉ ⲉⲧⲟⲩⲁⲁⲃ ⲥⲙⲟⲩ ⲣⲟⲓ ϯϯⲙⲉⲧⲁⲛⲟⲓⲁ | ϩⲁⲡϣⲟⲉⲓϣ ⲛⲛⲉⲧⲉⲛⲟⲩⲉⲣⲏⲧⲉ⸱ⲉⲧⲟⲩⲁⲁⲃ⸱ⲟⲩⲟⲛ | ⲛⲓⲙ ⲉⲧⲛⲁⲱϣ⸱ϩⲙⲡⲉⲓϫⲱⲱⲙⲉ⸱ⲁⲣⲓⲡⲙⲉⲉⲩⲉ | ⲙⲡⲉⲛⲙⲁⲓⲛⲟⲩⲧⲉ⸱ⲛⲥⲟⲛ ⲡⲁⲡⲁ <persName type="donor" ref="paths.persons.65">ⲉⲡⲓⲙⲁ</persName>⸱ⲡϣⲏⲣⲉ | (5) ⲙⲡⲙⲁⲕⲁⲣⲓⲟⲥ ⲙⲙⲁⲓ̈ⲛⲟⲩⲧⲉ ⲡⲁⲡⲁ <persName type="monk">ⲇⲁⲙⲓⲁⲛⲏ</persName>⸱ⲛⲧⲉ|ⲡⲛⲁⲏⲧ ⲛⲛⲟⲩⲧⲉ⸱ⲁⲩⲱ ⲛϣⲁⲛⲁϩⲧⲏϥ⸱ⲟⲓⲕⲟⲛⲟⲙⲉⲓ | ⲙⲡⲉϥⲃⲓⲟⲥ⸱ⲕⲁⲧⲁⲡⲉϥⲟⲩⲱϣ ⲉⲧⲟⲩⲁⲁⲃ⸱ⲁⲩⲱ | ⲛϥ̄ϫⲁⲕⲧⲉϥϩⲁⲏ ⲉⲃⲟⲗ⸱ⲕⲁⲗⲱⲥ⸱ϩⲛ︦ⲧⲉϥⲙⲉⲧⲉⲣⲟ | (10) ϫⲉⲛⲧⲟϥ⸱ⲁϥⲃⲓⲡⲉϥⲣⲟⲟⲩϣ⸱ϩⲙ̄ⲡⲉϥϩⲓⲥⲉ ⲙⲙⲓⲛ |ⲙⲙⲟϥ⸱ⲁϥⲧⲁⲁϥ ⲉϩⲟⲩⲛ ⲉⲡⲧⲟⲡⲟⲥ ⲙ<placeName type="monastery" ref="paths:place:99">ⲡⲁⲣⲭⲁⲅ|ⲅⲉⲗⲟⲥ ⲉⲧⲟⲩⲁⲁⲃ⸱ⲙⲓⲭⲁⲏⲗ⸱ⲡⲙⲟⲛⲁⲥⲧⲏⲣⲓⲟⲛ | ⲙⲡϩⲟⲛⲧⲟⲟⲩ</placeName>⸱ϩⲁⲡⲟⲩϫⲁⲓ | ⲛⲧⲉϥⲯⲩⲭ(ⲏ) ⲁⲩⲱ ⲥⲙⲟⲩ ⲣⲟⲓ | (15) ϯϯⲙⲉⲧⲁⲛⲟⲓⲁ⸱ϩⲱⲱⲧ⸱ⲙⲉϩ̣ⲕⲧⲏⲩⲧⲛ̄ ⲛⲙⲙⲁⲓ̈ | ⲙⲛⲡⲁⲕⲟⲩⲟⲓ ⲛϩⲱⲃ ⲛϭⲓϫ⸱ⲙⲟⲛ ⲛϯⲛⲟⲓ⸱ⲕⲁⲗⲱⲥ | ⲁⲣⲓⲡⲁⲙⲉⲉⲩⲉ⸱ⲛⲧⲉⲡⲛⲟⲩⲧⲉ ⲉⲣⲟⲩⲛⲁ⸱ⲛⲙⲙⲁⲓ̈⸱| ϩⲙⲡⲉϥⲃⲏⲙⲁ⸱ⲉⲧⲙⲉϩ ⲛϩⲟⲧⲉ ϩⲓⲥⲧⲱⲧ⸱| ϩⲁⲙⲏⲛ⸱ⲉⲥⲉϣⲱⲡⲉː-- | (20) ⳨ ἐγράφη μ(η)νὶ Φ(α)ω(φ)η ἰνδ(ικτίων)ο(ς) η ἔτου(ς) χρό(νων) σ︦λ︦ ἀπὸ Διοκλ(ητιανοῦ) φξ︦α︦ | ⳨ Ἐγὼ <persName type="copyist" ref="paths.persons.25">Ζαχαρί(α)ς</persName> ἐλ(ά)χ(ιστος) πρ(ε)σ(βύ)τ(ερος) κ(αὶ) <roleName type="religious">γαλιογράφου</roleName> δοῦλλος τοῦ <placeName type="monastery" ref="paths.place.100">ἁγίου μονα|στηρίου ὤρος Καλαμο̃νος</placeName> ἀμήν.
      </p>
    </body>
  </text>
</TEI>

=== paths-erc/coptic-texts/colophons/paths.colophons.225.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-model href="http://www.tei-c.org/release/xml/tei/custom/schema/relaxng/tei_ms.rng" type="application/xml"
schematypens="http://purl.oclc.org/dsdl/schematron"?>
<TEI xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="http://www.tei-c.org/ns/1.0 ../paths-schema.xsd"
  xmlns="http://www.tei-c.org/ns/1.0">
  <teiHeader>
    <fileDesc>
      <titleStmt>
        <title>paths.colophons 197</title>
      </titleStmt>
      <publicationStmt>
        <p>paths.colophons 197</p>
      </publicationStmt>
      <sourceDesc>
        <p>paths.colophons.197</p>
      </sourceDesc>
    </fileDesc>
  </teiHeader>
  <text>
    <body>
      <p>
        ⲁⲣⲓ ⲡⲛⲁ ⲛⲙ︥ⲙⲁⲓ̈ ⲁⲣⲓⲡⲁⲙⲉⲉⲩⲉ ϫⲉⲛ̄ⲧⲉ|ⲡⲛⲟⲩⲧⲉ ⲣⲟⲉⲓⲥ ⲉⲣⲟⲓ̈ ⲛϥ̄ⲛ̄ⲧⲁϩⲁⲏ⳿ | ⲉⲃⲟⲗ ⲉⲥ̣ⲣ̄ⲁⲛⲁϥ ⲁⲛⲟⲕ ⲡϣⲟⲓ̈ ⲕⲟⲩⲓ̈ | ⲡⲓⲉⲗⲁⲭ̣ ⲁⲓ̈ⲥⲉϩ ⲡⲉⲓ̈ϫⲱⲱⲙⲉ ϩⲁⲙⲏ(ⲛ)
      </p>
    </body>
  </text>
</TEI>

=== paths-erc/coptic-texts/colophons/paths.colophons.58.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-model href="http://www.tei-c.org/release/xml/tei/custom/schema/relaxng/tei_ms.rng" type="application/xml"
schematypens="http://purl.oclc.org/dsdl/schematron"?>
<TEI xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="http://www.tei-c.org/ns/1.0 ../paths-schema.xsd"
  xmlns="http://www.tei-c.org/ns/1.0">
  <teiHeader>
    <fileDesc>
      <titleStmt>
        <title>paths.colophons.58</title>
      </titleStmt>
      <publicationStmt>
        <p>paths.colophons.58</p>
      </publicationStmt>
      <sourceDesc>
        <p>paths.colophons.58</p>
      </sourceDesc>
    </fileDesc>
  </teiHeader>
  <text>
    <body>
      <p>
ⲡⲁⲓ̈ⲡⲉ ⲡϫⲱⲱⲙⲉ ⲛ̇ⲧⲁⲡⲙⲁⲓ̈ⲛⲟⲩ[ⲧⲉ] | ⲛ̄ⲥⲟⲛ ⲁⲡⲁ <persName type="donor">ⲕⲩⲣⲉ</persName> ϩ̄ⲙ̄ⲡ<placeName type="oratory">ⲏⲓ̈ ⲛ̄ⲛ̄ϣ̄ⲗ̄ⲕⲏⲧʾ</placeName> | ϥⲓ̄ⲡⲉϥⲣⲟⲟⲩϣ ⲁϥⲥⲁϩ̄ϥ̄ | ⲉϩⲟⲩⲛ ⲉⲡ<placeName type="oratory">ⲏⲓ̈ | ⲛ̄ⲛ̄ϣ̄ⲗ̄ⲕⲏⲧʾ</placeName> ⲉⲧⲣⲉⲩⲱϣ ⲛ̄ϩⲏⲧ̄ϥ̄ | (5) ϩⲛ̄ⲧϭⲏⲡⲉ ⲉⲩϩⲏⲩ ⲛ̄ⲧⲉϥⲯⲩⲭⲏ | ⲙⲛ̄ⲟⲩⲟⲛ ⲛⲓⲙ ⲉⲧⲛⲁⲥⲱⲧⲙ̄ ⲉⲣⲟϥ | ⲛ̄ⲥⲉⲉⲓⲣⲉ ⲕⲁⲧⲁⲛⲉⲧⲥⲏϩ ⲛ̄ϩⲏⲧ̄ϥ̄ | ⲁⲩⲱ ϫⲉⲕⲁⲥ ⲉⲣⲉⲡϫⲟⲉⲓⲥ ⲛⲁⲛ̄ⲧⲉϥϩⲁⲉ | ⲉⲃⲟⲗ ϩⲛ̄ⲛⲉϥⲧⲱⲡⲟⲥ ⲉⲧⲟⲩⲁⲁⲃ | (10) ⲛ̄ϥⲣ̄ⲟⲩⲛⲁ̄ ⲛ̄ⲙ̄ⲙⲁϥ ϩ̄ⲙ̄ⲡⲉϩⲟⲟⲩ | ⲙ̄ⲡⲉϥϭⲙ̄ⲡϣⲓⲛⲉ ϩⲛ̄ⲟⲩⲉⲓⲣⲏⲛⲏ | ϩⲁⲙⲏⲛ
    </p>
    </body>
  </text>
</TEI>

=== paths-erc/coptic-texts/colophons/paths.colophons.102.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-model href="http://www.tei-c.org/release/xml/tei/custom/schema/relaxng/tei_ms.rng" type="application/xml"
schematypens="http://purl.oclc.org/dsdl/schematron"?>
<TEI xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="http://www.tei-c.org/ns/1.0 ../paths-schema.xsd"
  xmlns="http://www.tei-c.org/ns/1.0">
  <teiHeader>
    <fileDesc>
      <titleStmt>
        <title>paths.colophons.102</title>
      </titleStmt>
      <publicationStmt>
        <p>paths.colophons.102</p>
      </publicationStmt>
      <sourceDesc>
        <p>paths.colophons.102</p>
      </sourceDesc>
    </fileDesc>
  </teiHeader>
  <text>
    <body>
      <p>
⳧ ϩⲙⲡⲣⲁⲛ ⲙⲡⲉⲓⲱⲧ ⲙ̣[ⲛⲡϣⲏⲣⲉ ⲙⲛⲡⲉⲡⲛ(ⲉⲩⲙ)ⲁ ⲉⲧⲟⲩⲁⲁⲃ] | ⲁⲛⲟⲕ ⲡⲓⲉⲗⲁⲭⲓⲥⲧ[ⲟⲥ ⲛ<roleName type="ecclesiastical">ⲇⲓⲁⲕⲟ]ⲛⲟⲥ</roleName> [ ± 11] | ⲛ̇ⲁⲡⲁ <persName type="donor" ref="paths.persons.135">ⲕⲟⲗⲟⲩⲑⲟⲥ</persName> · ⲡϣ[ⲏⲣ]ⲉ ⲛ̄ⲥⲭⲏⲙⲁ [ ± 9] | ⲁⲡⲓⲩⲛⲉ · ⲡ<roleName type="ecclesiastical">ⲣⲙ̄ⲛ̄ⲏⲓ̈</roleName> ⲙ̄ⲡⲉⲓⲏⲓ̈ · ⲫ · ⲙⲛ̄ⲓ̣[ ± 9] |(5)ⲭⲁⲏⲗ · ⲙⲛⲡϣⲟⲙⲧ ⲛⲥⲟⲛ ⲙⲙⲓⲥⲉ · ⲅ[± 10] | ⲙⲛ̄<persName type="donor" ref="paths.persons.136">ⲑⲉⲟⲇⲱⲣⲟⲥ</persName> ⲡⲛⲟϭ ⲙ̄<roleName type="ecclesiastical">ⲯⲁⲗⲙⲱⲇⲟⲥ</roleName> [± 9] | <roleName type="ecclesiastical">ⲇⲓⲁⲕⲟ(ⲛⲟⲥ)</roleName> ⲙⲛ̄ⲡⲁⲡⲁ <persName type="donor" ref="paths.persons.137">ϣⲉⲛⲟⲩⲧⲉ</persName> ⲙⲛ̄<persName type="donor" ref="paths.persons.138">ⲃⲓⲕⲧ[ⲱⲣ</persName> ± 7] | ⲉⲣⲉⲡⲁⲥⲟⲛ ⲛ̄ⲥⲭⲏⲙⲁ ⲡⲁⲡⲁ <persName type="monk">ⲙⲁⲣⲕⲟⲥ</persName> ⲟ ⲛ̄<roleName type="ecclesiastical">ⲣⲙ̄ⲛ̄ⲏⲓ̈</roleName> ⲉⲡⲓⲏ︦ⲓ︦ ⲫ | ⲁⲡⲉⲛⲉⲓⲱⲧ ⲙ̄ⲧⲟⲛ ⲙ̄ⲙⲟϥ · ⲁⲛⲉⲓ ⲉⲡⲉϥⲙⲁ · ⲁⲩⲱ ⲉⲓⲟ | (10) ⲙ̄ⲙⲉϩⲥⲛⲁⲩ ϩⲙ̄ⲡⲓⲏ︦ⲓ︦ · ⲁⲩⲱ ⲙ̄ⲙⲉϩϣⲟⲙⲧ̄ ⲛ<roleName type="ecclesiastical">ⲁⲣⲭⲏ|ⲇⲓⲁⲕⲟ(ⲛⲟⲥ)</roleName> ⲁⲩⲱ ⲛ̄<roleName type="ecclesiastical">ⲁⲡⲉ ϩⲛ̄ⲧⲥⲟⲟⲩϩⲥ̄</roleName> · ϩⲛ̄ⲧⲉⲓⲣⲟⲙⲡⲉ ⲧⲁⲓ | ⲥⲁⲣⲁⲕⲉⲛⲟⲥ · ⲧ︦ⲙ︦ⲋ︦ · ⲛ̄ⲧⲁⲛϩⲓⲧⲟⲟⲧⲛ̄ ⲉⲛⲉⲓϫⲱ[ⲱ]|ⲙⲉ ⲛ̄ⲗⲟⲅⲟⲥ · ⲙ̄ⲡⲉⲛⲉⲓⲱⲧ ⲁⲡⲁ <persName type="saint">ϣⲉⲛⲟⲩⲧⲉ</persName> ϫⲓ̣[ⲛ]|ⲧⲉⲩⲁⲣⲭⲏ · ϣⲁⲡⲉⲩϫⲱⲕ ⲉⲃⲟⲗ · ϩⲙ̇ⲡⲉⲥⲙⲟⲩ [ⲙⲡϫ(ⲟⲉⲓ)ⲥ | (15) ⲙⲛ̄ⲧⲃⲟⲏ̇ⲑⲓⲁ ⲙⲡⲛⲟⲩⲧⲉ · ⲙⲛ̄ⲛⲉϣⲗⲏ[ⲗ ⲛⲛⲉⲛⲉⲓⲟ]|ⲧⲉ ⲉⲧⲟⲩⲁⲁⲃ · ⲁⲛϥⲓⲡⲣⲟⲟⲩϣ · ⲛ̄[---] | ⲧⲟⲟⲧⲛ̄ · ⲁⲛⲥϩⲁⲓⲥⲟⲩ ⲉϩ[ⲟⲩⲛ ---] | ϩⲛ̄ⲧ̣[---] | [---]
verso
      </p>
    </body>
  </text>
</TEI>

=== paths-erc/coptic-texts/colophons/paths.colophons.63.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-model href="http://www.tei-c.org/release/xml/tei/custom/schema/relaxng/tei_ms.rng" type="application/xml"
schematypens="http://purl.oclc.org/dsdl/schematron"?>
<TEI xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="http://www.tei-c.org/ns/1.0 ../paths-schema.xsd"
  xmlns="http://www.tei-c.org/ns/1.0">
  <teiHeader>
    <fileDesc>
      <titleStmt>
        <title>paths.colophons.63</title>
      </titleStmt>
      <publicationStmt>
        <p>paths.colophons.63</p>
      </publicationStmt>
      <sourceDesc>
        <p>paths.colophons.63</p>
      </sourceDesc>
    </fileDesc>
  </teiHeader>
  <text>
    <body>
      <p>
ⲁⲣⲓ̄ⲡⲁⲙⲉⲉⲩ ⲛⲁⲅⲁⲡⲉ̄ ⲟⲩⲟⲛ ⲛⲓⲙ ⲉⲧⲛⲁⲱϣ ϩ̄ⲙ̄|ⲡⲓ̄ϫⲱⲱⲙⲉ⸱ⲉⲓⲥⲙⲉⲧⲁⲛⲟⲓ̄ⲁ⸱ⲕⲱ ⲛⲁⲓ̄ ⲉ̇ⲃⲟⲗ ⲛ̄|ⲛⲁϣⲟϥⲧ̄ⲥ̄⸱ⲛ̄ⲧⲁⲓϣⲱⲃⲧ̄ ⲛ̄ϩⲏⲧⲟⲩ̇⸱ϫⲉⲉⲓ̄ϫⲓⲥⲃⲱ̄ ː⸱| ⲡ⳪︦ ⲓⲥ︦ ⲡⲉⲭ̄ⲥ︦ ⲡⲉⲛⲥⲱⲧⲏⲣ⸱ⲉϥⲉⲥⲙⲟⲩ̇ ⲉ̄ⲡⲉⲛⲥⲟⲛ |(5) ⲙ̄ⲙⲁⲓ̈ⲛⲟⲩⲧⲉ⸱ⲛ<roleName type="ecclesiastical">ⲇⲓ̈ⲁⲕⲟⲛ</roleName>⸱[---] | ⲡϣⲏⲣⲉ ⲙⲡⲙⲁⲕⲁⲣⲓⲟⲥ [ ] | ⲙⲛ̄ⲛⲉϥϣⲏⲣⲉ⸱ϩ̄ⲛ̄ⲥⲙⲟⲩ ⲛⲓⲙ ⲙⲡⲛ(ⲉⲩⲙⲁⲧ)ⲓⲕⲟⲛ⸱ϫ̣ⲉ̣[ⲛ]|ⲧⲁϥϥⲉⲓ̈ⲡⲣⲟⲟⲩϣ⸱ⲙ̄ⲡⲉⲓ̄ϣⲟⲙ̄ⲛ̄ⲧ̄ ⲛ̄ⲕⲉⲫⲁⲗⲁⲓ̈ⲟⲛ | ⲛ̄ϫⲱⲱⲙⲉ⸱ⲉⲧⲉⲙ̄ⲡⲁⲣⲣⲟⲓ̄ⲙⲓ̄ⲁ⸱ⲛ̄ⲥⲟⲗⲱⲙⲟⲛ⸱|(10) ⲙⲛ̄ⲡⲉⲕⲕⲗⲉⲥⲓ̄ⲁⲥⲧⲏⲥ⸱ⲙⲛ̄ⲡϫⲱⲙⲉ ⲛ̣ⲓ̄ⲱⲃ⸱| ⲉⲧⲣⲉϥⲙⲉⲗⲉⲧⲁ ⲛ̄ϩⲏⲧⲟⲩ̇ ⲙ̄ⲛ̄ⲛⲉⲩ̣ϣⲏⲣⲉ⸱| ⲉⲩϩⲏⲩ ⲙⲛ̄ⲟⲩϫⲁⲓ̈ ⲛ̄ⲧⲉⲩⲯⲩⲭⲏ⸱ⲡ⳪︦ ⲓⲥ︦ ⲡⲉⲭ̄ⲥ︦ | ⲉ̇ϥⲉϩⲁⲣⲉϩ ⲉ̄ⲣⲱⲧⲛ̄⸱ⲛ̄ϥⲛ̄ⲧⲉⲧⲛ̣ϩⲁⲏ ⲉⲃⲟⲗ ⲕⲁⲗ̣ⲱ̣ⲥ | ⲉⲥϫⲏⲕ ⲉ̄ⲃⲟⲗ⸱ⲛϥⲣ̄ⲧⲉⲩⲧⲛ̄ ⲛⲙⲡϣⲁ ⲛ̣ⲧⲉϥ|(15)ⲥⲙⲏ ⲛ̄ⲣⲁϣⲉ⸱ⲉϥϫⲱ ⲙ̄ⲙⲟⲥ ϫⲉⲁⲙⲏⲓⲧⲛ ϣⲁⲣⲟⲓ̈ | ⲛⲉⲧⲥⲙⲁⲙⲁⲁⲧ ⲛ̄ⲧⲉⲡⲁⲓ̄ⲱⲧ⸱ⲛ̄ⲧⲉⲧⲛ̄ⲕⲗⲏⲣⲟⲛⲟ|ⲙⲉⲓ̈ ⲛ̄ⲉⲓ̄ⲁⲅⲁⲑⲟⲛ⸱ⲙⲛ̄ⲛⲉ̣ⲥ̣ⲛ̣ⲏ̣ⲩ ⲧⲏⲣⲟⲩ ⲛ̄|ⲭⲣⲓ̣ⲥϯⲁⲛⲟⲥ⸱ⲁⲙⲏⲛ⸱ⲉϥⲉϣⲱⲡⲉ
    </p>
    </body>
  </text>
</TEI>

=== paths-erc/coptic-texts/colophons/paths.colophons.86.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-model href="http://www.tei-c.org/release/xml/tei/custom/schema/relaxng/tei_ms.rng" type="application/xml"
schematypens="http://purl.oclc.org/dsdl/schematron"?>
<TEI xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="http://www.tei-c.org/ns/1.0 ../paths-schema.xsd"
  xmlns="http://www.tei-c.org/ns/1.0">
  <teiHeader>
    <fileDesc>
      <titleStmt>
        <title>paths.colophons.86</title>
      </titleStmt>
      <publicationStmt>
        <p>paths.colophons.86</p>
      </publicationStmt>
      <sourceDesc>
        <p>paths.colophons.86</p>
      </sourceDesc>
    </fileDesc>
  </teiHeader>
  <text>
    <body>
      <p>
ⲡⲟⲟⲩ ⲡⲁⲓ ⲓⲉ︦ ⲙⲡⲁⲱⲛⲉ | ϯⲣⲟⲙⲡⲉ ⲧⲁⲓ ⲭⲣ(ⲟⲛⲟⲥ) ⲙⲁⲣⲧ(ⲩⲣⲱⲛ) ⲯⲝ̄ⲑ︦ | ⲥⲁⲣⲁⲅⲉⲛⲟ(ⲛ) ⲩ︤ⲙ︦︤ⲏ︥ ⲉⲣⲉⲡⲉ|ⲭⲥ︦ ⲟ ⲛⲉⲣ̇ⲣⲟ ϩⲓϫⲱⲛ ϩⲁⲙⲏⲛ |(5) ⲁⲣⲓⲡⲁⲙⲉⲉⲩⲉ ⲛⲁⲅⲁⲡⲏ· | ⲁⲛⲟⲕ ⲡⲓⲣ̄ϥⲣ̄ⲛⲟⲃⲉ ⲙ̇ⲡ|ⲁⲣⲁⲡⲕⲁϩ· ⲧⲏⲣϥ̇· ⲡⲓ̈|ⲁⲧⲙ̇ϣⲁ ⲙ̄ⲡⲓⲣⲁⲛ ϫⲉⲇⲓ[(ⲁⲕⲟⲛⲟⲥ) | <persName type="copyist">ⲙⲣ︥ⲕⲟⲩⲣⲉ · ⲡⲩ(ⲓⲟ)ⲥ ⲙ̇ⲡ ̣[ |(10) ⲡⲁⲙⲉⲟⲥ</persName> ⲁⲣⲓⲡⲁⲙⲉⲩⲉ ⲛⲁ̣|ⲅⲁⲡⲏ · ϫⲉⲁⲛⲅ̈ⲟⲩ[ⲥⲃ|ⲟⲩⲓ· ⲙ̇ⲡⲁϯⲛⲟⲓ ⲕⲁⲗⲟ(ⲥ) [ⲁⲗ|ⲗⲁ ⲉⲓⲥϫ[ⲓ]ⲥⲃⲱ ⲛ̣̇[ |  ̣ ̣ ̣]ⲛⲁⲡ̣̣̣ | - - - - - - -

ⲡ⳪︦ ⲡⲉⲛⲧⲁϥ]ϫⲓ ⲛ̄ⲛⲉⲇ[ⲱⲣⲟⲛ ⲛ<persName type="biblical">ⲁⲃⲉⲗ</persName> ⲡⲇⲓⲕⲁⲓⲟⲥ ⲙⲛ]|[ⲧⲉⲑⲩⲥⲓ]ⲁ̣ ⲙ̇ⲡⲛ̇ⲉⲓⲱⲧ [<persName type="biblical">ⲁⲃⲣⲁϩⲁⲙ</persName> ⲙⲛⲡⲗⲉⲡⲧⲟⲛⲥⲛⲁⲩ  ̣]  ̣ ̣[ | ⲛ̣ⲧⲉ<persName type="biblical">ⲭⲏⲣⲁ</persName> · ⲛⲓⲣⲏⲛ[---<persName type="donor">]|ⲁⲗⲙⲟⲥ ⲙⲡⲉⲛⲉⲓⲱⲧ [---] |(5) ⲙ̇ⲡⲛ̇ⲙⲁⲓⲛⲟⲩⲧⲉ ⲛ[---] | ⲡⲩ(ⲓⲟ)ⲥ ⲙⲙ̇ⲁϣⲛ̇ⲕ̇ⲁ</persName> · ⲙⲛ[  ̣ ̣ ̣]ⲙⲁⲁ[ | ⲡⲁⲡⲧⲟϣ <placeName type="city_village" ref="paths:places:000">ⲡⲁⲭⲱⲣⲁⲥ</placeName> ⲛⲧⲉ<placeName type="country" ref="paths:places:000">ⲛⲟ̣ⲡⲟⲇⲓⲁ</placeName> · ϫ[ⲉⲛⲧⲟϥ] | ⲡⲛ̇ⲧⲁϥϫⲱ ⲉⲃⲟⲗ ϩⲛⲛⲉϥϩⲓⲥⲉ ⲙⲙⲓⲛ ⲙⲙⲟϥ ⲁϥⲥ|ⲙⲛ̇ⲡⲓⲕⲁⲓⲫⲁⲗⲁⲓⲟⲛ ⲛϫⲱⲱⲙⲉ · ⲁϥⲕⲁⲁϥ ϩⲛⲧⲕ̇|(10)ⲕⲗⲏⲥⲓⲁ · ⲙ̇<placeName type="church_basilica" ref="paths:places:000">ⲡ(ⲥⲧⲁⲩⲣ)ⲟⲥ</placeName> ⲙ<placeName type="city_village" ref="paths:places:000">ⲡⲧⲉⲥⲉⲣⲣⲁϩ</placeName> ϩⲁⲡⲟⲩϫⲁⲓ ⲛ̇|ⲧϥ̇ⲯⲩⲭⲏ · ⲉⲣⲉⲡⲛⲟⲩⲧⲉ ⲥⲙⲟⲩ ⲉⲣⲟϥ ϩⲛ̇ⲥ|ⲥⲙⲟⲩ ⲛⲓⲙ ⲙ̇ⲡⲛ(ⲉⲩⲙⲁⲧ)ⲓⲕⲱⲛ · ⲁⲩⲱ ⲛⲉⲡⲟⲩⲣⲁⲛⲓⲟⲛ · | ⲛⲧⲟϥ ⲙⲛ̇ⲧϥ̇ⲥϩⲓⲙⲉ ⲙⲛ̇ⲛⲉϥϣⲏⲣⲉ ⲙⲛ̇ⲉⲛⲕⲁ | ⲛⲓⲙ ⲉⲧⲛ̇ⲧϥ̇ · ⲛϥ̇ⲥϩⲁⲓ ⲉⲡϥ̇ⲣⲁⲛ ⲉⲡϫⲱⲱⲙⲉ ⲙ̇|(15)ⲡⲱⲛϩ · ⲛϥ̇ⲁⲁϥ ⲛⲙ̇ϣⲁ · ⲙ̇ⲡⲣⲁϣⲉ ⲛ̇ⲧϥ̇ⲁⲛ|ⲁⲥⲧⲁⲥⲓⲥ · ⲙⲛ̇ⲛϥ̇ⲡⲉⲧⲟⲩⲁⲁⲃ ⲧⲏⲣⲟ(ⲩ) ϩⲁⲙⲏⲛ· | ⲟⲩⲛⲁ ⲙ́ⲡⲉⲧⲥϩⲁⲓ · ⲟⲩⲥⲟⲟⲩⲛ ⲙ̇ⲡⲉⲧⲱϣ · ⲟⲩⲙⲉ|ⲧⲁⲛⲟⲓⲁ ⲙ̇ⲡⲧ̇ⲥⲱⲧⲙ̇ · ϩⲁⲙⲏⲛ ⲉⲥⲉϣⲱⲡⲉ. | ⲓ(ⲏⲥⲟ)ⲩ ⲭ(ⲣⲓⲥⲧⲟ)ⲩ ⲑ(ⲉⲟ)ⲩ ⲭⲁⲣⲓⲛ
      </p>
    </body>
  </text>
</TEI>

=== paths-erc/coptic-texts/colophons/paths.colophons.17.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-model href="http://www.tei-c.org/release/xml/tei/custom/schema/relaxng/tei_ms.rng" type="application/xml"
schematypens="http://purl.oclc.org/dsdl/schematron"?>
<TEI xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="http://www.tei-c.org/ns/1.0 ../paths-schema.xsd"
  xmlns="http://www.tei-c.org/ns/1.0">
  <teiHeader>
    <fileDesc>
      <titleStmt>
        <title>paths.colophons.17</title>
      </titleStmt>
      <publicationStmt>
        <p>paths.colophons.17</p>
      </publicationStmt>
      <sourceDesc>
        <p>paths.colophons.17</p>
      </sourceDesc>
    </fileDesc>
  </teiHeader>
  <text>
    <body>
      <p>
ⲉⲕⲱ︦ <persName type="copyist">ⲅⲁⲃⲣⲓ̈</persName> <roleName type="ecclesiastical">ⲇ(ⲓⲁ)ⲕ(ⲟⲛⲟⲥ)</roleName> | ⲉⲗⲁⲭⲓ̈ⲥⲧⲟⲩ‧ | (ⲕⲁⲓ) <persName type="copyist">ⲙⲁⲣⲕⲟⲩⲣⲉ</persName> | ⲡⲉ̣ϥϣⲏⲣⲉ‧ | (5) ⲁⲡⲱ <placeName type="city_village">ⲭⲱⲣⲓ̈ⲟⲩ ⲛ|ⲑ̣[ⲉ]ⲱⲕⲉⲛⲓ̈ⲧⲟⲥ</placeName>‧ | [ⲉⲧⲉ]ⲡⲉⲣⲡⲛⲟⲩ|[ⲧⲉ] ⲡⲉ ϩ̣ⲙ̣̄ⲡ̇ⲧⲟϣ | <placeName type="district_nomos">[ⲡⲓ]ⲟ̣ⲙ</placeName> ⲉⲕ︦ⲣ︦ⲁ︦ⲯⲁⲧ(ⲟ)? | (10) [ⲁⲡⲟ ⲇ]ⲓⲟⲕⲗⲏⲇⲓ̈|ⲁⲛⲟⲩ‧ⲭ︦ⲓ︦ⲑ︦ | ⲁⲩⲱ̇ ⲛⲧⲁⲡⲓ̈ⲁⲕⲁ|ⲑⲱⲛ ϣ̄ⲱⲡⲉ ϩⲛ̄|ⲛⲉϩⲟⲟⲩ ⲙ̇ⲡⲁⲉⲓⲱⲧ | (15) ⲡ<roleName type="ecclesiastical">ⲇⲓ̣(ⲁⲕⲟⲛⲟⲥ)</roleName> <persName type="monk">[ϩⲏⲗ]ⲓ̣ⲁ̣</persName> ⲡ<roleName type="ecclesiastical">ⲓⲕⲟ|ⲛⲟⲙ̣ⲟⲥ</roleName> ⲉ<placeName type="monastery">ⲙ̣ⲓⲭⲁⲏⲗ</placeName> | ⲉⲣⲉⲡ︦⳪︦ ⲥⲙⲟⲩ ⲉⲣⲟϥ | ⲉⲣⲉⲛⲉⲥ̇ⲙⲟⲩ ⲛⲡⲓ|ⲱⲧ ⲙⲛⲡϣⲏⲣⲉ | (20)	ⲙⲛⲡⲉⲡⲛ︦ⲁ̄ ⲉⲧⲟⲩ|ⲁⲁⲃ ‧ ⲉⲓ̈ ⲉϫⲛ̇ⲧⲁ|ⲡⲉ ⲛⲧⲛ̇ⲙⲁⲓ̈ⲛⲟⲩ|ⲧⲉ ⲛⲥⲱⲛⲉ ‧ <persName type="donor">ⲑⲁ|ⲛⲁⲥⲓ̈ⲁ ‧ ⲧϣⲛ̇ⲁ|(25)ⲛⲁⲥⲧⲁⲥⲓⲁ</persName> ‧ ϫⲉ|ⲛⲧⲟⲥ ⲁ`ⲥ´ϥⲓⲡⲣⲟ|ⲟⲩϣ ⲙⲡⲓϫⲱⲱ|ⲙⲉ ‧ ϩⲛ̄ⲛⲉⲥϩⲓ̈|ⲥⲉ ⲙ̇ⲙ̇ⲓ̈ⲛ ⲉⲙ̇ⲙⲟⲥ ‧|(30) ⲁⲥⲧⲁⲁⲃ ⲉϩⲟⲩⲛ̇ | ⲧⲉⲕⲕⲗⲏⲥ̇ⲓ̈ⲁ ⲙ̇|ⲡⲉⲥϯⲙⲉ ‧ <placeName type="monastery">ⲙⲓ̈|ⲭⲁⲏⲗ</placeName> ⲛ<placeName type="city_village">ⲥⲱ|ⲡⲉϩⲉⲥ</placeName> ‧ ϩⲁⲡⲟⲩ|(35)ϫⲁⲓ ⲛⲧⲉⲥⲯⲩⲭⲏ̇ | ϫⲉⲕⲁⲥ ⲉⲣⲉⲡⲛⲟⲩ|ⲧⲉ ⲙⲛ<persName type="arch_angel">ⲁⲣⲭⲁⲅⲅⲉ|ⲗⲟⲥ ⲙⲓ̈ⲭⲁⲏⲗ</persName> ‧ ⲥ|ⲙⲟⲩ ⲉⲣⲟⲥ ‧ ⲁⲩⲱ̇ |(40)	ⲛⲧⲉⲡⲛⲟⲩⲧ(ⲉ) ⲡⲁⲕⲁ̇|ⲑⲟⲥ ϯ ⲛⲁⲥ ⲛⲧϣⲉ|ϥⲓ̈ⲱ ⲛⲛⲉⲥⲉⲣⲏⲧ̇ | ϩⲛ̇ⲑⲓ̈ⲗ︦ⲏ︦ⲙ︦ ⲛⲧ|ⲡⲉ ‧ ϩⲁⲙⲏⲛ ⲉⲥⲉ|(45)ϣⲱⲡⲉ —
      </p>
    </body>
  </text>
</TEI>
