=== paths-erc/coptic-texts/paths-schema.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified" targetNamespace="http://www.tei-c.org/ns/1.0" xmlns:ns1="http://www.tei-c.org/ns/1.0">

  <xs:element name="TEI">

    <xs:complexType>
      <xs:sequence>
        <xs:element ref="ns1:teiHeader"/>
        <xs:element ref="ns1:text"/>
      </xs:sequence>
    </xs:complexType>

  </xs:element>

  <xs:element name="teiHeader">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="ns1:fileDesc"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="fileDesc">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="ns1:titleStmt"/>
        <xs:element ref="ns1:publicationStmt"/>
        <xs:element ref="ns1:sourceDesc"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="titleStmt">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="ns1:title"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="title" type="xs:string"/>
  <xs:element name="publicationStmt">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="ns1:p"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="sourceDesc">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="ns1:p"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="text">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="ns1:body"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="body">
    <xs:complexType>
      <xs:sequence>
        <xs:element maxOccurs="unbounded" ref="ns1:p"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>

  <xs:element name="p">
    <xs:complexType mixed="true">
      <xs:choice minOccurs="0" maxOccurs="unbounded">
        <xs:element ref="ns1:date"/>
        <xs:element ref="ns1:gap"/>
        <xs:element ref="ns1:lb"/>
        <xs:element ref="ns1:persName"/>
        <xs:element ref="ns1:placeName"/>
        <xs:element ref="ns1:roleName"/>
        <xs:element ref="ns1:quote"/>
        <xs:element ref="ns1:org"/>
        <xs:element ref="ns1:rs"/>
      </xs:choice>
      <xs:attribute name="n" type="xs:integer" use="optional" />
    </xs:complexType>
  </xs:element>

  <xs:element name="date">
    <xs:complexType mixed="true">
      <xs:choice minOccurs="0" maxOccurs="unbounded">
        <xs:element ref="ns1:lb"/>
      </xs:choice>
      <xs:attribute name="type" use="required">
        <xs:simpleType>
          <xs:restriction base="xs:string">
            <xs:enumeration value="commemoration" />
            <xs:enumeration value="official_feast" />
            <xs:enumeration value="concilia" />
            <xs:enumeration value="liturgies_ceremonies" />
          </xs:restriction>
        </xs:simpleType>
      </xs:attribute>
    </xs:complexType>
  </xs:element>

  <xs:element name="gap">
    <xs:complexType/>
  </xs:element>
  <xs:element name="lb">
    <xs:complexType/>
  </xs:element>

  <xs:element name="persName">
    <xs:complexType mixed="true">
      <xs:choice minOccurs="0" maxOccurs="unbounded">
        <xs:element ref="ns1:lb"/>
        <xs:element ref="ns1:roleName"/>
      </xs:choice>
      <xs:attribute name="ref" use="optional" />
      <xs:attribute name="type" use="required">
        <xs:simpleType>
          <xs:restriction base="xs:string">
            <xs:enumeration value="saint" />
            <xs:enumeration value="martyr" />
            <xs:enumeration value="apostle" />
            <xs:enumeration value="bishop" />
            <xs:enumeration value="archi_bishop" />
            <xs:enumeration value="monk" />

            <xs:enumeration value="arch_angel" />
            <xs:enumeration value="daemon" />

            <xs:enumeration value="emperor_king" />
            <xs:enumeration value="civil" />
            <xs:enumeration value="military" />
            <xs:enumeration value="ecclesiastical" />
            <xs:enumeration value="biblical" />
            <xs:enumeration value="pagan_deity" />

            <xs:enumeration value="donor" />
            <xs:enumeration value="copyist" />
            <xs:enumeration value="restorer" />
          </xs:restriction>
        </xs:simpleType>
      </xs:attribute>
    </xs:complexType>
  </xs:element>


  <xs:element name="placeName">
    <xs:complexType mixed="true">
   	  <xs:choice minOccurs="0" maxOccurs="unbounded">
        <xs:element ref="ns1:persName"/>
        <xs:element ref="ns1:lb"/>
      </xs:choice>
      <xs:attribute name="ref" use="optional" />
      <xs:attribute name="subtype" use="optional">
        <xs:simpleType>
          <xs:restriction base="xs:string">
            <!-- Admin places -->
            <xs:enumeration value="egyptian" />
            <xs:enumeration value="non_egyptian" />
          </xs:restriction>
        </xs:simpleType>
      </xs:attribute>
      <xs:attribute name="type" use="required">
        <xs:simpleType>
          <xs:restriction base="xs:string">
            <!-- Admin places -->
            <xs:enumeration value="country" />
            <xs:enumeration value="region" />
            <xs:enumeration value="district_nomos" />
            <xs:enumeration value="city_village" />
            <xs:enumeration value="topos_ma" />
            <!-- Religios places -->
            <xs:enumeration value="monastery" />
            <xs:enumeration value="church_basilica" />
            <xs:enumeration value="episkopeion" />
            <xs:enumeration value="chapel" />
            <xs:enumeration value="oratory" />
            <xs:enumeration value="martyr_shrine" />
            <xs:enumeration value="temple" />
            <xs:enumeration value="hermitage" />
            <xs:enumeration value="tomb" />
            <!-- Natural fetures -->
            <xs:enumeration value="mount" />
            <xs:enumeration value="river" />
            <xs:enumeration value="lake" />
            <xs:enumeration value="harbour" />
            <!-- Lit -->
            <xs:enumeration value="biblical" />
          </xs:restriction>
        </xs:simpleType>
      </xs:attribute>
    </xs:complexType>
  </xs:element>

  <xs:element name="roleName">
    <xs:complexType mixed="true">
      <xs:choice minOccurs="0" maxOccurs="unbounded">
        <xs:element ref="ns1:lb"/>
      </xs:choice>
      <xs:attribute name="ref" use="optional" />
      <xs:attribute name="type" use="required">
        <xs:simpleType>
          <xs:restriction base="xs:string">
            <xs:enumeration value="religious" />
            <xs:enumeration value="ecclesiastical" />
            <xs:enumeration value="civil" />
            <xs:enumeration value="military" />
          </xs:restriction>
        </xs:simpleType>
      </xs:attribute>
    </xs:complexType>
  </xs:element>

  <xs:element name="org">
    <xs:complexType mixed="true">
      <xs:choice minOccurs="0" maxOccurs="unbounded">
        <xs:element ref="ns1:lb"/>
      </xs:choice>
      <xs:attribute name="ref" use="optional" />
      <xs:attribute name="type" use="required">
        <xs:simpleType>
          <xs:restriction base="xs:string">
            <xs:enumeration value="religious" />
            <xs:enumeration value="ethnic" />
          </xs:restriction>
        </xs:simpleType>
      </xs:attribute>
    </xs:complexType>
  </xs:element>

  <xs:element name="quote">
    <xs:complexType mixed="true">
      <xs:choice minOccurs="0" maxOccurs="unbounded">
      	<xs:element ref="ns1:date"/>
        <xs:element ref="ns1:gap"/>
        <xs:element ref="ns1:lb"/>
        <xs:element ref="ns1:persName"/>
        <xs:element ref="ns1:placeName"/>
        <xs:element ref="ns1:roleName"/>
        <xs:element ref="ns1:org"/>
        <xs:element ref="ns1:rs"/>
      </xs:choice>
      <xs:attribute name="ref" use="optional" />
      <xs:attribute name="type" use="required">
        <xs:simpleType>
          <xs:restriction base="xs:string">
            <xs:enumeration value="biblical" />
            <xs:enumeration value="classical" />
          </xs:restriction>
        </xs:simpleType>
      </xs:attribute>
    </xs:complexType>
  </xs:element>

  <xs:element name="rs">
    <xs:complexType mixed="true">
      <xs:choice minOccurs="0" maxOccurs="unbounded">
        <xs:element ref="ns1:lb"/>
      </xs:choice>
      <xs:attribute name="ref" use="optional" />
      <xs:attribute name="type" use="required">
        <xs:simpleType>
          <xs:restriction base="xs:string">
            <xs:enumeration value="object" />
            <xs:enumeration value="furniture" />
            <xs:enumeration value="service" />
          </xs:restriction>
        </xs:simpleType>
      </xs:attribute>
    </xs:complexType>
  </xs:element>

</xs:schema>

=== paths-erc/coptic-texts/colophons/paths.colophons.201.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-model href="http://www.tei-c.org/release/xml/tei/custom/schema/relaxng/tei_ms.rng" type="application/xml"
schematypens="http://purl.oclc.org/dsdl/schematron"?>
<TEI xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="http://www.tei-c.org/ns/1.0 ../paths-schema.xsd"
  xmlns="http://www.tei-c.org/ns/1.0">
  <teiHeader>
    <fileDesc>
      <titleStmt>
        <title>paths.colophons 197</title>
      </titleStmt>
      <publicationStmt>
        <p>paths.colophons 197</p>
      </publicationStmt>
      <sourceDesc>
        <p>paths.colophons.197</p>
      </sourceDesc>
    </fileDesc>
  </teiHeader>
  <text>
    <body>
      <p>
        fol. 120r

μνήσθυτη κ(ύρι)ε δοῦ δούλους σου ἐλαχ(ίστου) διακό(νου) | Γαβριήλ υ(ἱο)ῦ Μηνᾶ π[±3]αυ ἀπὸ χωρ(ί)ο(υ) Νιμανθωμς | συνθρόνο(υ) Θμουι (καὶ) Τκεϩλι συνχώριζον | τὸν παραπτώματα ἱμῶν ἀμήν χρόνου Μ(α)ρτ(ύρων) χϙε
      </p>
    </body>
  </text>
</TEI>

=== paths-erc/coptic-texts/colophons/paths.colophons.175.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-model href="http://www.tei-c.org/release/xml/tei/custom/schema/relaxng/tei_ms.rng" type="application/xml"
schematypens="http://purl.oclc.org/dsdl/schematron"?>
<TEI xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="http://www.tei-c.org/ns/1.0 ../paths-schema.xsd"
  xmlns="http://www.tei-c.org/ns/1.0">
  <teiHeader>
    <fileDesc>
      <titleStmt>
        <title>paths.colophons.175</title>
      </titleStmt>
      <publicationStmt>
        <p>paths.colophons.175</p>
      </publicationStmt>
      <sourceDesc>
        <p>paths.colophons.175</p>
      </sourceDesc>
    </fileDesc>
  </teiHeader>
  <text>
    <body>
      <p>
ⲡⲁⲓⲗⲟⲅⲟⲥ ⲫⲁⲡⲁⲓⲱⲧ ⲡ(ⲁ)ⲡ(ⲁ) <persName type="donor" ref="paths.persons.197">ⲍⲁⲭⲁⲣⲓⲁ</persName>· (ⲟⲩⲟϩ) ⲡⲁⲥⲟⲛ <persName type="donor" ref="paths.persons.198">ⲓ̇ⲉⲣⲉⲙⲓⲁⲥ</persName> ⲡⲉϥⲥⲟⲛ (ⲟⲩⲟϩ) ⲡⲁⲥⲟⲛ <persName type="donor" ref="paths.persons.199">ⲅⲁⲩⲣⲓⲏⲗ</persName> ⲡⲟ︦ⲥ︦ ⲓ︦ⲏ︦ⲥ︦ ⲡⲭ︦ⲥ︦ ⲥⲙⲟⲩ ⲉⲣⲱⲟⲩ (ⲟⲩⲟϩ) ⲛ̔ⲧⲉϥϯⲙ̇ⲧⲟⲛ ⲛ̇ⲧⲯⲩⲭ(ⲏ) ⲉⲙⲡⲁⲓⲱⲧ ⲡ(ⲁ)ⲡ(ⲁ) ⲛⲓϫⲓ ⲡⲟⲩⲓⲱⲧ ⲁⲙⲏⲛ
    </p>
    </body>
  </text>
</TEI>

=== paths-erc/coptic-texts/colophons/paths.colophons.106.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-model href="http://www.tei-c.org/release/xml/tei/custom/schema/relaxng/tei_ms.rng" type="application/xml"
schematypens="http://purl.oclc.org/dsdl/schematron"?>
<TEI xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="http://www.tei-c.org/ns/1.0 ../paths-schema.xsd"
  xmlns="http://www.tei-c.org/ns/1.0">
  <teiHeader>
    <fileDesc>
      <titleStmt>
        <title>paths.colophons.106</title>
      </titleStmt>
      <publicationStmt>
        <p>paths.colophons.106</p>
      </publicationStmt>
      <sourceDesc>
        <p>paths.colophons.106</p>
      </sourceDesc>
    </fileDesc>
  </teiHeader>
  <text>
    <body>
      <p>
ⲡ(ϫ)ⲟ(ⲉⲓ)ⲥ ⲓ(ⲏⲥⲟⲩ)ⲥ ⲡⲉⲭ(ⲣⲓⲥⲧⲟ)ⲥ ⲥⲙⲟⲩ ⲉⲡ|ⲙⲁⲓⲛⲟⲩⲧⲉ ⲛⲥⲁⲛ ⲛ̄|ⲧⲁϥϥⲓⲡⲣⲟⲟⲩϣ ⲙ̄|ⲡⲓϫⲱⲱⲙⲉ ⲁϥⲧⲁ|(5)ⲁϥ ⲉϩⲟⲩⲛ ⲉⲡ<placeName type="monastery" ref="paths:places:99">ⲧⲟⲡⲟⲥ | ⲙ̄ⲡⲁⲣⲭⲁⲅⲅⲉⲗⲟⲥ ⲉ|ⲧⲟⲩⲁⲁⲃ ⲙⲓⲭⲁⲏⲗ ⲙ|ⲫⲁ̣ⲩ̣</placeName> ϣⲗⲏⲗ ⲉϫⲉⲙⲡⲉⲛ|ⲧⲁϥϥⲓⲡⲉϥⲣⲟⲟⲩϣ | (10) ⲛⲧⲉⲡⲛⲟⲩⲧⲉ ⲥ̄ⲙⲟⲩ ⲉ̄|ⲣⲟϥ · ⲁⲩⲱ ⲛ̇ϥϯ ⲛⲁϥ | ⲛ̄ⲧϣⲉⲃⲓⲱ̄ ⲙⲡⲉϥ|ⲉⲣⲏⲧ ϩⲛ̄ⲑⲓ(ⲉⲣⲟⲩⲥⲁ)ⲗⲏⲙ ⲛ̄ⲧ|ⲡⲉ ϩⲁⲙⲏⲛ ⲉⲥⲉϣⲱⲡⲓ̈ :-
      </p>
    </body>
  </text>
</TEI>

=== paths-erc/coptic-texts/colophons/paths.colophons.31.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-model href="http://www.tei-c.org/release/xml/tei/custom/schema/relaxng/tei_ms.rng" type="application/xml"
schematypens="http://purl.oclc.org/dsdl/schematron"?>
<TEI xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="http://www.tei-c.org/ns/1.0 ../paths-schema.xsd"
  xmlns="http://www.tei-c.org/ns/1.0">
  <teiHeader>
    <fileDesc>
      <titleStmt>
        <title>paths.colophons.31</title>
      </titleStmt>
      <publicationStmt>
        <p>paths.colophons.31</p>
      </publicationStmt>
      <sourceDesc>
        <p>paths.colophons.31</p>
      </sourceDesc>
    </fileDesc>
  </teiHeader>
  <text>
    <body>
      <p>
ⲛ̄ⲧⲁⲡⲉⲓⲁⲅⲁⲑ(ⲟⲥ) ϣⲱⲡⲉ ⲉⲃⲟⲗ ϩⲓⲧⲟ|ⲟⲧϥ̄ ⲙ̄ⲡⲙⲁⲓⲛⲟⲩⲧⲉ ⲛ̇ⲥⲟⲛ·ⲉⲧⲧ(ⲁⲓⲏⲩ) | <persName type="donor">ⲯⲁⲧⲉ</persName>⸱ⲛ̇ⲣ︤ⲙ︥<placeName type="city_village" ref="paths:places:353">ⲧⲙⲉⲕⲣⲁ</placeName>⸱ϩⲙ̇ⲡⲧⲟϣ | ⲛ̄<placeName type="district_nomos" ref="paths:places:70">ⲣ̄ⲙⲟⲛ︤ⲧ︥</placeName>⸱| (5) ⲉⲣⲉⲡϫ(ⲟⲉⲓ)ⲥ ⲡⲛⲟⲩⲧⲉ ⲙⲡ<persName type="arch_angel">ⲁⲣⲭⲁⲅⲅⲉⲗⲟⲥ | ⲉⲧⲟⲩⲁⲁⲃ ϩⲣⲁⲫⲁⲏⲗ</persName> ⲙ︤ⲛ︥ⲡ<persName type="saint">ⲁⲅⲓⲟⲥ ⲡⲁⲩⲗⲟⲥ | ⲡⲁⲡⲟⲥⲧⲟⲗⲟⲥ</persName>⸱ⲛⲁⲥⲙⲟⲩ ⲉⲣⲟϥ ⲛ̇ⲧⲟϥ <persName type="donor">ⲯⲁⲧⲉ</persName> | ⲙⲛ̇ⲧⲉϥⲥϩⲓⲙⲉ ⲙ︤ⲛ︥ⲛⲉϥϣⲏⲣⲉ⸱ⲙ︤ⲛ︥ⲧⲉϥ|ϭⲓⲛⲣ̄ϩⲱⲃ⸱ⲛϥ̄ⲁⲁϥ ⲛ̄ⲥⲩⲛⲕⲗⲏⲣⲟⲛⲟⲙⲟⲥ |(10) ⲙ︤ⲛ︥ⲛⲉϥⲡⲉⲧⲟⲩⲁⲁⲃ ϩⲣⲁⲓ ϩⲛ̄ⲧⲉϥⲙ︤ⲛ︦ⲧ︥|ⲉⲣⲟ ⲉⲧϩⲛ̄ⲙ̄ⲙ̄ⲡⲏⲩⲉ⸱ϣⲁⲉⲛⲉϩ⸱ϩⲁⲙⲏⲛ | <persName type="copyist">Ἰωσήφ ἐλαχΐστου ϥ(ιο)ῦ Σίσιννϊς</persName> ἐγράφη ⸱Ἀθυρ⸱ϛ | ἔτους Σ̣α̣ρ̣α̣κ̣η̣[νῶν | τ︤μ︦θ̣︥
    </p>
    </body>
  </text>
</TEI>

=== paths-erc/coptic-texts/colophons/paths.colophons.71.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-model href="http://www.tei-c.org/release/xml/tei/custom/schema/relaxng/tei_ms.rng" type="application/xml"
schematypens="http://purl.oclc.org/dsdl/schematron"?>
<TEI xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="http://www.tei-c.org/ns/1.0 ../paths-schema.xsd"
  xmlns="http://www.tei-c.org/ns/1.0">
  <teiHeader>
    <fileDesc>
      <titleStmt>
        <title>paths.colophons.70</title>
      </titleStmt>
      <publicationStmt>
        <p>paths.colophons.70</p>
      </publicationStmt>
      <sourceDesc>
        <p>paths.colophons.70</p>
      </sourceDesc>
    </fileDesc>
  </teiHeader>
  <text>
    <body>
      <p>
[ϩ]ⲙⲡⲟⲩⲱϣ ⲙⲡⲛⲟⲩⲧⲉ ⲙ̄ⲛ̄ⲛⲉϣⲗⲏⲗʾ ⲙ̄ⲡⲉⲛϫⲟⲓ̈ⲥ | [ⲛ]ⲉⲓⲱⲧʾ ⲉⲧⲟⲩⲁⲁⲃʾ ⲙ̄ⲡⲣⲟⲫⲏⲧⲏⲥ ⲡϩⲁⲅⲓⲟⲥ ⲁⲡⲁ ϣⲉ|[ⲛ]ⲟⲩⲧⲉ ⲡⲁⲣⲭⲓⲙⲁⲛⲇⲣⲓⲧⲏⲥ ⲙ̄ⲛ̄ⲧⲙ̄ⲛ̄ⲧϥⲁⲓ̈ⲣ(ⲟ)`ⲩ´ϣ | [ⲛ]ⲧⲛ̄ⲑⲉⲟⲁⲣⲏⲥⲧⲟⲥ ⲛ̄ϫⲟⲉⲓⲥ ⲙ̄ⲙⲁⲁⲩ ⲉⲧⲥⲙⲁⲙⲁⲁⲧ | (5) [ⲁⲩⲱ] ⲉⲧⲧⲁⲏⲩ ⲕⲁⲧⲁ[ⲥ]ⲙⲟⲧʾ ⲛⲓⲙʾ ⲁⲙⲙⲁ ⲙⲁⲛⲛⲟⲩ | [ⲧⲛ]ⲟϭ ⲛ̣ⲁⲣⲭⲁⲙⲁⲛⲇⲣⲓⲧⲏⲥ ⲁⲩⲱ ⲧⲁⲣⲭⲏⲅⲟⲥ | [ⲁⲩ]ⲱ ⲧϩⲩⲅⲟⲩⲙⲉⲛⲏⲥⲥⲁ · ⲙ̄ⲛ̄ⲁⲙⲁ ⲕⲩⲣⲁ ⲑⲉⲱ|[ⲇ]ⲱ̣ⲣⲁ ϣⲏⲙ ⲧⲉϣⲉⲉⲣⲉ ⲛ̄ⲧⲁⲩⲥ̄ⲙ̄ⲛ̄ⲡⲉⲓ̈ϫⲱⲱⲙⲉ | [ϩⲛ]ⲧⲉⲩⲛⲟϭ ⲙ̄ⲙⲉʾ ⲉϩⲟⲩⲛ ⲉⲡⲛⲟⲩⲧⲉʾ ⲛ̄ⲧⲁⲥⲡⲟⲩⲧⲁ|(10)[ⲍⲉ] ⲅⲁⲣ ⲁⲥⲥ̄ⲙ̄ⲛ̄ⲡⲉⲓ̈ⲛⲟϭ · ⲛ̄ⲕⲉⲫⲁⲗⲁⲓⲟⲛ ϩ̄ⲛ̄ⲧⲙⲉϩ|[ϫⲟ]ⲩⲧⲥⲛⲟⲟⲩⲥʾ ⲛ̄ⲣⲟⲙⲡⲉ ⲛ̄ⲧⲉⲥⲃⲁⲥⲓⲗⲉⲓⲁʾ ⲉⲥⲟ̄ ⲛ̄ϩⲁ|[ⲅ]ⲓⲁ ⲇⲏⲥⲡⲱⲧⲁʾ ⲉⲥⲁⲣⲭⲉⲓ ⲉϩⲣⲁⲓ̈ ⲉϫ̄ⲙ̄ⲡⲉⲥⲗⲁⲟⲥ | [ⲧ]ⲏⲣ̄ϥ ⲛ̄ⲉⲩⲗⲟⲅⲏⲙⲉⲛⲟⲥ · ⲡⲛⲟⲩⲧⲉ ⲡⲁⲓⲱⲛⲓ|[ⲟⲥ] ⲙⲁⲩⲁⲁϥʾ ⲉϥⲛⲁⲭⲁⲣⲓⲍⲉ ⲛⲁⲥ ⲛ̄ⲟⲩⲛⲟϭ ⲛ̄ⲁϩⲉʾ | (15) [ⲙⲛ]ϩⲉⲛⲣ̄ⲙ̄ⲡⲟⲟⲩⲉ ⲛⲁϣⲱⲟⲩ ⲛ̄ϥ̄ⲕⲁⲡⲉⲕⲣⲁ|[ⲧⲟ]ⲥ̣ ⲛ̄ⲁⲓⲱⲛⲓⲟⲛ, ⲁⲩⲱ ⲛ̄ⲁⲩⲧⲱⲕⲣⲁⲧⲱⲣ · | [ϩⲛ]ⲧⲉⲥⲙ̄ⲛ̄ⲧ̄ⲉⲣⲟ, ⲉϥⲧⲁϩⲏⲩ ⲉⲣⲁⲧ̄ϥ̄ ⲉϥⲙⲏⲛʾ | [ⲉ]ⲃ̣ⲟⲗʾ ϣⲁⲡⲇⲏⲗⲓⲟⲛ ⲙ̄ⲡⲕⲟⲥⲙⲟⲥ, ⲛ̄ϥ̄ⲇⲓⲟⲓ|ⲕⲉ ⲙ̄ⲡⲉⲥⲃⲓⲟⲥ ⲡⲣⲟⲥⲡⲉϥⲟⲩⲱϣ, ⲛ̄ϥ̄ϯ ⲛⲁⲥ | (20)	ⲛ̄ⲟⲩⲙⲉⲣⲓⲥ, ⲙ̄ⲛ̄ⲟⲩⲕⲗⲏⲣⲟⲥ ⲙ̄ⲛ̄ⲡⲉⲧⲟⲩ|ⲁⲁⲃʾ ⲧⲏⲣⲟⲩ · ⲛ̄ϥ̄ⲧⲣⲉⲥⲥⲱⲧ̄ⲙ̄ ⲉⲧⲉⲓ̈ⲥⲙⲏ̄ ⲙ̄ⲙⲁ|ⲕⲁⲣⲓⲟⲛ ⲉⲧⲙⲉϩʾ ⲛ̄ⲣⲁϣⲉ, ϫⲉⲁⲙⲏⲉⲓⲧ̄ⲛ̄ ⲛⲉⲧ|ⲥⲙⲁⲙⲁⲁⲧʾ ⲛ̄ⲧⲉⲡⲁⲉⲓⲧʾ ⲛ̄ⲧⲉⲧ̄ⲛ̄ⲕⲗⲏⲣⲟⲛⲟ|ⲙⲉⲓ ⲛ̄ⲧⲙ̄ⲛ̄ⲧ̄ⲉⲣⲟ ⲛ̄ⲧⲁⲩⲥ̄ⲃ̄ⲧⲱⲧ̄ⲥ̄ ⲛⲏⲧ̄ⲛ̄ | (25) ϫⲓⲛⲧⲕⲁⲧⲁⲃⲟⲗⲏ ⲙ̄ⲡⲕⲟⲥⲙⲟⲥ · ⲅⲉⲛⲉⲧⲟ | ⲅⲉⲛⲉⲧⲟʾ · ⲑⲉⲟⲩ, ⲭⲁⲣⲓⲥ; ⲛⲓⲕⲁ · ⲁⲙⲏⲛ :
    </p>
    </body>
  </text>
</TEI>

=== paths-erc/coptic-texts/colophons/paths.colophons.41.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-model href="http://www.tei-c.org/release/xml/tei/custom/schema/relaxng/tei_ms.rng" type="application/xml"
schematypens="http://purl.oclc.org/dsdl/schematron"?>
<TEI xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="http://www.tei-c.org/ns/1.0 ../paths-schema.xsd"
  xmlns="http://www.tei-c.org/ns/1.0">
  <teiHeader>
    <fileDesc>
      <titleStmt>
        <title>paths.colophons.41</title>
      </titleStmt>
      <publicationStmt>
        <p>paths.colophons.41</p>
      </publicationStmt>
      <sourceDesc>
        <p>paths.colophons.41</p>
      </sourceDesc>
    </fileDesc>
  </teiHeader>
  <text>
    <body>
      <p>
ⲉⲅⲱ ⲉⲗⲁⲭ(ⲓⲥⲧⲟⲥ) <persName type="copyist" ref="paths.persons.45">ⲙⲱⲩⲥⲏⲥ</persName> | ⲅⲁⲗⲓⲟⲅⲣⲁⲫⲟⲥ | ⲡϫⲟⲉⲓⲥ ⲓ(ⲏⲥⲟⲩ)ⲥ ⲡ(ⲉⲭⲣⲓⲥⲧⲟ)ⲥ ⲡⲉⲓⲱⲧ | ⲉⲡⲉⲛϫⲟⲉⲓⲥ ⲓ(ⲏⲥⲟⲩ)ⲥ ⲡ(ⲉⲭⲣⲓⲥⲧⲟ)ⲥ⸳ⲡⲉⲛ|(5)ⲧⲁϥϫⲓ ⲛⲛⲉⲛⲧⲱⲣⲛ | ⲛⲁⲃⲉⲗ ⲡⲇⲓⲕⲁⲓⲟⲥ⸳ⲙⲛ|ⲧⲉⲑⲉⲥⲓⲁ ⲙⲡⲉⲛⲉⲓⲱⲧ ⲁⲃ|ⲣⲁϩⲁⲙ ⲙⲛⲡⲗⲉⲡⲧⲟⲛ | ⲥⲩⲛⲁⲩ ⲛⲧⲉⲭⲏⲣⲁ ⲉϥⲉⲥ|(10)ⲙⲟⲩ ⲉⲡⲉⲛⲙⲁⲓⲛⲟⲩⲧⲉ ⲛ|ⲥⲟⲛ <persName type="donor" ref="paths.persons.87">ⲡⲁϩⲱⲙⲁ</persName> ⲙⲛⲧⲉϥ|ⲥϩⲓⲙⲉ ⲙⲉⲛⲛⲉϥϣⲏⲣⲉ | ⲙⲛⲛⲕⲁ ⲛⲓⲙ ⲉⲧϣⲟⲟⲡ | ⲛⲁϥ⸳ϫⲉⲛⲧⲟϥ ⲁϥⲃⲓⲡ|(15)ⲣⲟⲟⲩϣ ⲙⲡⲉⲓⲕⲉⲫⲁⲗⲉ|ⲟⲛ ⲛϫⲱⲱⲙⲉ ⲁϥⲥ|ⲙⲛⲧϥ ϩⲉⲛⲛⲉϥϩⲓⲥⲉ ⲙ|ⲙⲙⲓⲛ ⲉⲙⲉⲙⲙⲟⲩ⸳ⲁϥⲧⲁ|ⲁϥ ⲉϩⲟⲩⲛ ⲉⲧⲕⲟⲩⲓ ⲛ<placeName type="church_basilica" ref="paths.places.357">ⲉⲕ|(20)ⲗⲉⲥⲓⲁ⸳ⲁⲡⲁⲧⲓⲙⲟⲑⲉ ⲛⲧ|ⲙⲟⲩⲟⲩ</placeName> ϩⲁⲡⲟⲩϫⲁⲓ ⲛⲧⲉϥ|ⲯⲩⲭⲏ⸳ⲉⲣⲉⲡⲛⲟⲩⲧⲉ ⲛ|ⲛⲉϣⲗⲏⲗ ⲉⲡⲡⲉⲧⲟⲩⲁⲁⲃ | ⲡⲁⲓ ⲛⲧⲁϥⲉⲣⲡⲉⲩⲙⲉⲉⲩⲉ | (25) ⲛⲁⲥⲙⲟⲩ ⲉⲣⲟⲟⲩ ϩⲙⲡⲕⲟⲥ|ⲙⲟⲥ ⲙⲛⲛⲕⲁ ⲛⲓⲙ ⲉⲧϣⲟ|ⲟⲡ ⲛⲁϥ⸳ⲁⲩⲱ ⲟⲛ ⲉϥϣⲁⲛ|ⲉⲓ ⲉⲃⲟⲗ ϩⲉⲛⲥⲱⲙⲁ ⲛϥⲕ|ⲗⲏⲣⲟⲛⲟⲙⲓⲁ ⲛⲧⲙⲛⲧⲣⲟ ⲛ|(30)ⲛⲉⲙⲡⲏⲩⲉ ⲙⲛⲛⲉⲥⲁⲕⲁ|ⲑⲟⲛ ϩⲁⲙⲏⲛ ⲉⲥⲉϣⲱ|ⲡⲓ
    </p>
    </body>
  </text>
</TEI>

=== paths-erc/coptic-texts/colophons/paths.colophons.54.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-model href="http://www.tei-c.org/release/xml/tei/custom/schema/relaxng/tei_ms.rng" type="application/xml"
schematypens="http://purl.oclc.org/dsdl/schematron"?>
<TEI xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="http://www.tei-c.org/ns/1.0 ../paths-schema.xsd"
  xmlns="http://www.tei-c.org/ns/1.0">
  <teiHeader>
    <fileDesc>
      <titleStmt>
        <title>paths.colophons.54</title>
      </titleStmt>
      <publicationStmt>
        <p>paths.colophons.54</p>
      </publicationStmt>
      <sourceDesc>
        <p>paths.colophons.54</p>
      </sourceDesc>
    </fileDesc>
  </teiHeader>
  <text>
    <body>
      <p>
⳧ ⲡⲉⲓⲱⲧ ⲙⲛ̇ⲡ̇ϣⲏⲣⲉ ⲙⲛ̇ⲡⲉⲡⲛ̄ⲁ̄ ⲉⲧⲟⲩⲁⲁⲃ | ⲉ̇ϥⲉⲥⲙⲟⲩ ⲁⲩⲱ ⲛϥϩⲁⲣⲉϩ ⲉⲡⲱⲛϩ ⲙⲡⲉⲛ|ⲙⲟⲓ̈ⲛⲟⲩⲧ(ⲉ) ⲛ̇ϭ̄ⲥ̄ ⲛⲁⲣⲭⲉⲧⲧⲁ(ⲓⲏⲩ) ⲁⲩⲱ ⲛ̇<roleName type="religious">ⲁⲥⲕⲩⲧⲏⲥ</roleName> | ⲡⲁⲥⲟⲛ <persName type="donor">ⲕⲁⲩⲣⲓ̈ⲏⲗ</persName>⸱ϫⲉⲛⲧⲟϥ ⲁϥϥⲉⲓ̈ | (5) ⲙ̇ⲡⲣⲟⲟⲩϣ ⲙ̇ⲡⲉⲓⲕⲉⲫⲁⲗⲁⲓ̈ⲟⲛ ⲛ̇ϫⲱⲱ̇ⲙⲉ | ϩⲛ̇ⲛⲉϥϩⲓ̈ⲥⲉ ⲙ̇ⲙⲓ̈ⲛ ⲙⲙⲟϥ⸱ⲁϥⲧⲁⲁϥ ⲉϩⲟⲩⲛ | ⲉ<placeName type="monastery"></placeName>ⲡⲁⲣⲭⲁⲅⲅⲉⲗⲟⲥ ⲙⲓⲭⲁⲏⲗ</placeName> ⲉ<placeName type="city_village">ⲡϩⲁⲛⲧⲟⲟⲩ</placeName>⸱| ϩⲁⲡⲥⲱⲧⲉ ⲛ̇ⲧⲉϥⲯⲩⲭⲏ⸱ϫⲉⲕⲁⲥ ⲉ̇ⲣⲉⲡ<persName type="arch_angel">ⲁⲣⲭⲁⲅ|ⲅⲉⲗⲟⲥ ⲙⲓ̈ⲭⲁⲏⲗ</persName> ⲡⲁⲣⲁⲕⲁⲗⲉⲓ ⲙ̇ⲡⲣⲣ̇ⲟ ⲡⲉⲭ̄ⲥ̄ ⲉϩ|(10)ⲣⲁⲓ̈ ϩⲓ̈ϫⲱϥ ⲛ̇̇ϥ̇ⲕⲱ ⲛⲁϥ ⲉ̇ⲃⲟⲗ ⲛ̇ⲛⲉϥⲛⲟⲃⲉ⸱| ⲛ̇ϥ̇ϯ ⲛⲁϥ ⲛ̇ⲛⲁⲧⲡⲉ ⲛ̇ϣⲉϥⲉⲓ̈ⲱ ⲛ̇ⲛⲁⲡⲕⲁϩ ⲛⲓ̈ϣⲁⲉⲓ̈|ⲛⲉϩ ⲉⲡⲙⲁ ⲛ̇ⲛⲓ̈ⲡⲣⲟⲥⲟⲩⲟ̇ⲉⲓ̈ϣ⸱ⲁⲩⲱ̇ ⲛ̇ϥ̇ϯ ⲛⲧϣⲉⲃⲉⲓⲱ | ⲙ̇ⲡⲉⲃⲉⲣⲏⲧ ⲛⲁϥ ⲛ̇ⲣ̄ ⲛ̇ⲕⲱϥ ⲛ̇ⲥⲟⲡ ϩⲛ̇ⲑⲓⲗ̄ⲏ̄ⲙ̄ ⲉⲧⲡⲉ ⲧⲡⲟⲗ(ⲓⲥ) | ⲛ̇ⲛⲉⲛⲇⲓ̈ⲕⲁⲓ̈ⲟⲥ ⲧⲏⲣⲟⲩ⸱ⲁⲩⲱ̇ ⲉϥϣⲁⲛⲓ̈ ⲉⲃⲟⲗ ϩⲙ̇ⲡⲓⲃⲓ̈ⲟⲥ | (15) ⲛ̇ϥⲙ̇ⲡ̇ϣⲁ ⲛ̇ⲥⲱⲧⲙ̇ ⲉϯⲥⲙⲏ ⲉⲧⲙⲏϩ ⲛ̇ⲣⲁϣⲉ⸱ϩⲓ̈ⲉⲩⲫⲣⲟⲥⲩⲛⲏ | ⲛⲓ̈ⲙ ⲛ̇ⲧⲉⲡⲉⲭ̄ⲥ̄⸱ϫⲉⲁ̇ⲙⲟⲩ ⲡⲉⲧⲥⲙⲁⲙⲁⲁⲧ ⲛ̇ⲧⲏⲓ ⲁⲗⲓ̈ⲕⲗⲏⲣⲟ|ⲛⲟⲙⲉⲓ̈ ⲛ̇ⲛⲉⲓ̈ⲁⲅⲁⲑⲟⲛ ⲛ̇ⲧⲁⲓ̈ⲥⲃ̇ⲧⲱⲧⲟⲩ ⲛⲁⲕ⸱ⲉ̇ⲥⲉϣⲱⲡⲉ ⲙ̇ⲙⲟ(ⲛ) | ⲧⲏⲣ̇ⲛ⸱ⲛⲉⲧⲥϩⲁⲓ̈ ⲛⲉⲧⲱϣ⸱ⲛⲉⲧⲥⲱⲧⲙ ϩⲁⲙⲏⲛ ⲉⲥⲉϣⲱⲡⲉ | ⳧ ⲁⲩⲱ ⲁ̇ⲣⲓ̈ⲡⲙⲉⲉⲩⲉ̇ ⲙ̇ⲡⲉⲛϭ̄ⲥ̄ ⲛ̇ⲓⲱⲧ ⲙ̇ⲡⲛ(ⲉⲩⲙⲁⲧⲓⲕ)ⲟ(ⲥ) ⲕⲩⲣⲱ ⲡⲁⲉⲓⲱⲧ ⲡ<roleName type="ecclesiastical">ⲇⲓⲁⲕⲟ(ⲛⲟⲥ)</roleName> | (20) <persName type="monk">ⲓ̄ⲱ̄ⲁ̄ⲛ̄ⲛ</persName> ⲡ<roleName type="ecclesiastical">ⲁⲣⲭⲏⲙⲁⲧⲣⲓ̈ⲧⲏⲥ</roleName> ⲙ̇<placeName type="monastery" ref="paths:places:99">ⲡⲁⲣⲭⲁⲅⲅⲉⲗⲟⲥ ⲙⲓ̈ⲭⲁⲏⲗ ⲉⲡϩⲁⲛⲧⲟⲟⲩ</placeName> | ⲛ̇ⲧⲉⲡϭ̄ⲥ̄ ⲡ̇ⲛⲟⲩⲧ(ⲉ) ⲥ̇ⲙⲟⲩ ⲉ̇ⲣⲟϥ⸱ⲙⲛⲛⲉϥⲥ̇ⲛⲏⲩ⸱ⲙⲛ̇ⲛⲉϥⲣⲱⲙⲉ ⲧⲏⲣⲟⲩ | ⲛⲉⲧⲏⲡ ⲉⲣⲟϥ⸱ⲙ̇ⲛⲛⲉⲧⲛ̇ⲥⲉⲏⲡ ⲉⲣⲟϥ ⲁⲛ⸱ⲛ̇ⲧⲉⲡ̇ⲛⲟⲩϯ ϯⲟⲩⲛⲟϭ | ⲛⲟϩⲉ ⲛⲁϥ⸱ⲛ̇ϥ̇ϯⲭⲁⲣⲓ̈ⲥ ⲉ̇ⲡⲉϥϩⲟ ⲙ̇ⲡⲉⲙⲧⲟ ⲉ̇ⲃⲟⲗ⸱ⲉⲣⲱⲙⲉ ⲛⲓ̈ⲙ⸱ⲙⲛ̇ⲛⲓ̈ⲉⲝⲟⲩ|ⲥⲓⲁ ⲉⲩϫⲟⲥⲉ⸱ⲉϥⲥ̇ⲙⲟⲩ ⲉ̇ⲣⲱⲙⲉ ⲛⲓ̈ⲙ ⲉⲧϣⲟⲟⲡ ϩⲁⲧⲉϥϩⲩⲡⲟⲧⲁⲕⲏ⸱| (25) ⲛ̇ϥ̇ϫⲟⲕϥ̇ ⲉ̇ⲃⲟⲗ ϩⲉⲡⲉⲥⲭⲏⲙⲁ ⲉ̇ⲧⲟⲩⲁⲁⲃ⸱ⲛ̇ⲛⲁⲅⲅⲉⲗⲟⲥ⸱ⲛ̇ϥ̇ⲕⲱ ⲉⲃⲟⲗ | ⲛ̇ⲛⲉϥⲛⲟⲃⲉ⸱ϣⲁⲉⲛⲉϩ ϩⲁⲙⲏⲛ | ⲁⲣⲓ̈ⲡⲁⲙⲉⲉⲩⲉ ϩⲱⲱⲧ ⲛⲁⲅⲁⲡⲏ ⲟⲩⲟⲛ ⲛⲓⲙ ⲉⲧⲛⲁⲱϣ ϩⲙ̇ⲡⲓ̈ϫⲱⲱⲙⲉ ϣⲗⲏⲗ | ϩⲓ̈ϫⲱⲛ̇ ⲁⲛⲟⲕⲡⲉ <persName type="copyist">ⲓ̈ⲥⲁⲁⲕ</persName> ⲡⲉⲧⲙ̇ⲡ̇ϣⲁ ⲁⲛ ⲉⲡⲣⲁⲛ ⲉⲛⲧⲁⲩⲧⲁⲟⲩⲟϥ ⲉϩⲣⲁⲓ ⲉϫⲱϥ⸱ | ϫⲉ<roleName type="ecclesiastical">ⲡⲣ(ⲉ)ⲥ(ⲃⲩⲧⲉⲣⲟⲥ)</roleName> ⸱ⲙⲛ̇ⲡ<roleName type="ecclesiastical">ⲇⲓ(ⲁⲕⲟⲛⲟⲥ)</roleName> <persName type="copyist">ⲁⲣⲭⲏⲗⲗⲓⲧ( )</persName>⸱ⲙⲛ<persName type="copyist">ⲓ̈ⲱϩⲁⲛⲛⲏⲥ</persName> ⲕⲟⲥⲙⲓⲕⲟⲛ⸱ⲛⲉϣⲏⲣⲉ ⲙ̇ⲡ̇|(30)ⲙⲁⲕⲁⲣⲓⲟⲥ ⲡ<roleName type="ecclesiastical">ⲇⲓⲁⲕⲟ(ⲛⲟⲥ)</roleName> <persName type="monk">ⲓⲱⲥⲏⲫ</persName> ⲛⲁ<placeName type="city_village" ref="paths:places:218">ⲡⲧⲉⲡⲟⲩϩⲁⲣ</placeName> ⲉ<placeName type="district_nomos" ref="paths:places:323">ⲡⲓ̈ⲟⲙ</placeName>⸱ϣⲗⲏⲗ ϩⲓϫⲱⲛ⸱| ⲁⲩⲱ ϥⲉⲓ̈ ϩⲁⲣⲟⲛ ⲙ̇ⲛⲡⲉⲛⲕⲟⲩⲓ̈ ⲛ̇ϩⲱⲃ ⲛ̇ϭⲓϫ ⲉⲧϭⲟϫϥ ϫⲉ̣ⲙⲏⲡⲱⲧⲉ ⲉⲁⲛⲉⲛⲛⲟⲩⲥ | ϣⲱϥⲧ̇ ⲛⲟⲩⲗⲉⲝⲓⲥ ⲉⲃⲟⲗ ⲛ̇ϩⲏⲧϥ̇ ⲁⲩⲱ̇ ϫⲉⲙⲉⲁⲧϣⲱϥⲧ̇ ⲛ̇ⲥⲁⲡⲧⲉⲥ|ⲡⲱⲧⲏⲥ ⲙ̇ⲙⲁⲩⲁⲁϥ⸱ⲁⲩⲱ̇ ⲛ̇ⲧⲁⲛⲥ̇ϩⲁⲓ̈ ⲕⲁⲧⲁⲡⲁⲛϯⲓⲕⲣⲁⲫⲟⲛ ⲉⲧϩⲁ|ⲣⲟⲛ ⲁⲡⲟ ⲇⲓⲟⲕⲗⲏⲧ(ⲓⲁⲛⲟⲩ) ⲕⲁⲧⲁ ⲭⲣⲟⲛⲟⲛ ⲙⲁⲩⲧⲩⲣⲟⲛ ⲭ̄ⲑ̄ ⲥ(ⲁ)ⲣ(ⲁⲕⲏⲛⲱⲛ) ⲥ̄ⲟ̄ⲏ̄
</p>
    </body>
  </text>
</TEI>

=== paths-erc/coptic-texts/colophons/paths.colophons.66.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-model href="http://www.tei-c.org/release/xml/tei/custom/schema/relaxng/tei_ms.rng" type="application/xml"
schematypens="http://purl.oclc.org/dsdl/schematron"?>
<TEI xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="http://www.tei-c.org/ns/1.0 ../paths-schema.xsd"
  xmlns="http://www.tei-c.org/ns/1.0">
  <teiHeader>
    <fileDesc>
      <titleStmt>
        <title>paths.colophons.65</title>
      </titleStmt>
      <publicationStmt>
        <p>paths.colophons.65</p>
      </publicationStmt>
      <sourceDesc>
        <p>paths.colophons.65</p>
      </sourceDesc>
    </fileDesc>
  </teiHeader>
  <text>
    <body>
      <p>
ⲁⲩⲱ ⲛ̇ⲧⲁⲡⲉⲓⲁⲅⲁⲑⲟⲛ | ϣⲱⲡⲉ ⲉⲃⲟⲗ ϩⲓⲧⲟⲟ|ⲧⲥ ⲛ̇ⲧⲙⲛⲧⲃⲁⲓⲣⲟⲟⲩϣ | ⲙ̄ⲡⲉⲛⲙⲁⲓⲛⲟⲩⲧ(ⲉ ) ⲛⲥⲟⲛ | (5) ⲁⲩⲱ ⲛ<roleName type="ecclesiastical">ⲉⲕⲟⲓⲛⲟⲙⲟⲥ</roleName> ⲡ<roleName type="ecclesiastical">ⲙ`ⲟ´|ⲛⲁⲭⲟⲥ</roleName> ϩⲛⲟⲩⲙⲉ ⲉⲣⲉⲡⲛⲟⲩⲧ(ⲉ) | ⲉϥⲉϩⲁⲣⲉϩ ⲉⲣⲟϥ ⲛϥϯ|ⲑⲉ ⲛⲁϥ ⲉⲧⲣⲉϥϫⲏⲕ | ⲡⲉϥⲃⲓⲟⲥ ϩⲛⲟⲩⲙ̣ⲛⲧ|(10)ⲕⲁⲑⲁⲣⲟⲥ ⲛϥ̇ϣⲱⲡ̄ | ⲙⲛ̄ⲡⲉϥⲉⲓⲱⲧ ⲁⲡⲁ | <persName type="saint">ϣⲉⲛⲟⲩⲧ(ⲉ)</persName> ⲉⲃⲟⲗ ϫⲉⲛ|ⲧⲟϥ ⲡⲉⲛⲧⲁϥϥⲡⲣⲟⲟⲩϣ | ⲙⲡⲓϫⲱⲱⲙⲉ ⲁϥⲕⲁ|(15)ⲁϥ ϩⲛ̄ⲧⲕⲁⲑⲉⲇⲣⲁ | ⲙ<placeName type="monastery">ⲡⲉⲡⲣⲟⲫⲏⲧⲏⲥ ⲁⲡⲁ | ϣⲉⲛⲟⲩⲧ(ⲉ)</placeName> ⲙⲡⲧⲟⲟⲩ ⲛ<placeName type="city_village">ⲁⲧⲣⲓⲡ̄</placeName> | ⲛⲧⲟϥ ⲡⲥⲟ ⲉⲧⲙ̄ⲙⲁⲩ <persName type="donor">ⲃⲁⲥ̄ⲓ︦ⲗ︦</persName> | ⲟⲩⲙⲁⲓⲛⲉⲅⲣⲁⲫⲏⲡⲉ ⲉϥⲟⲩ|(20)ⲱϣ ⲉⲧⲣⲉⲟⲩⲟⲛ ⲛⲓⲙ ϯϩⲏⲧ | ⲉⲧⲃⲉⲡⲁⲓ ⲁϥⲥⲩⲛϩⲓⲥⲧⲁ | ⲙⲡⲓϫⲱⲱⲙⲉ ⲙⲛⲛⲥⲁ | ⲧⲣⲉϥⲧⲁⲕⲟ
    </p>
    </body>
  </text>
</TEI>
