=== paths-erc/coptic-texts/paths-schema.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified" targetNamespace="http://www.tei-c.org/ns/1.0" xmlns:ns1="http://www.tei-c.org/ns/1.0">

  <xs:element name="TEI">

    <xs:complexType>
      <xs:sequence>
        <xs:element ref="ns1:teiHeader"/>
        <xs:element ref="ns1:text"/>
      </xs:sequence>
    </xs:complexType>

  </xs:element>

  <xs:element name="teiHeader">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="ns1:fileDesc"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="fileDesc">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="ns1:titleStmt"/>
        <xs:element ref="ns1:publicationStmt"/>
        <xs:element ref="ns1:sourceDesc"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="titleStmt">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="ns1:title"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="title" type="xs:string"/>
  <xs:element name="publicationStmt">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="ns1:p"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="sourceDesc">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="ns1:p"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="text">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="ns1:body"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="body">
    <xs:complexType>
      <xs:sequence>
        <xs:element maxOccurs="unbounded" ref="ns1:p"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>

  <xs:element name="p">
    <xs:complexType mixed="true">
      <xs:choice minOccurs="0" maxOccurs="unbounded">
        <xs:element ref="ns1:date"/>
        <xs:element ref="ns1:gap"/>
        <xs:element ref="ns1:lb"/>
        <xs:element ref="ns1:persName"/>
        <xs:element ref="ns1:placeName"/>
        <xs:element ref="ns1:roleName"/>
        <xs:element ref="ns1:quote"/>
        <xs:element ref="ns1:org"/>
        <xs:element ref="ns1:rs"/>
      </xs:choice>
      <xs:attribute name="n" type="xs:integer" use="optional" />
    </xs:complexType>
  </xs:element>

  <xs:element name="date">
    <xs:complexType mixed="true">
      <xs:choice minOccurs="0" maxOccurs="unbounded">
        <xs:element ref="ns1:lb"/>
      </xs:choice>
      <xs:attribute name="type" use="required">
        <xs:simpleType>
          <xs:restriction base="xs:string">
            <xs:enumeration value="commemoration" />
            <xs:enumeration value="official_feast" />
            <xs:enumeration value="concilia" />
            <xs:enumeration value="liturgies_ceremonies" />
          </xs:restriction>
        </xs:simpleType>
      </xs:attribute>
    </xs:complexType>
  </xs:element>

  <xs:element name="gap">
    <xs:complexType/>
  </xs:element>
  <xs:element name="lb">
    <xs:complexType/>
  </xs:element>

  <xs:element name="persName">
    <xs:complexType mixed="true">
      <xs:choice minOccurs="0" maxOccurs="unbounded">
        <xs:element ref="ns1:lb"/>
        <xs:element ref="ns1:roleName"/>
      </xs:choice>
      <xs:attribute name="ref" use="optional" />
      <xs:attribute name="type" use="required">
        <xs:simpleType>
          <xs:restriction base="xs:string">
            <xs:enumeration value="saint" />
            <xs:enumeration value="martyr" />
            <xs:enumeration value="apostle" />
            <xs:enumeration value="bishop" />
            <xs:enumeration value="archi_bishop" />
            <xs:enumeration value="monk" />

            <xs:enumeration value="arch_angel" />
            <xs:enumeration value="daemon" />

            <xs:enumeration value="emperor_king" />
            <xs:enumeration value="civil" />
            <xs:enumeration value="military" />
            <xs:enumeration value="ecclesiastical" />
            <xs:enumeration value="biblical" />
            <xs:enumeration value="pagan_deity" />

            <xs:enumeration value="donor" />
            <xs:enumeration value="copyist" />
            <xs:enumeration value="restorer" />
          </xs:restriction>
        </xs:simpleType>
      </xs:attribute>
    </xs:complexType>
  </xs:element>


  <xs:element name="placeName">
    <xs:complexType mixed="true">
   	  <xs:choice minOccurs="0" maxOccurs="unbounded">
        <xs:element ref="ns1:persName"/>
        <xs:element ref="ns1:lb"/>
      </xs:choice>
      <xs:attribute name="ref" use="optional" />
      <xs:attribute name="subtype" use="optional">
        <xs:simpleType>
          <xs:restriction base="xs:string">
            <!-- Admin places -->
            <xs:enumeration value="egyptian" />
            <xs:enumeration value="non_egyptian" />
          </xs:restriction>
        </xs:simpleType>
      </xs:attribute>
      <xs:attribute name="type" use="required">
        <xs:simpleType>
          <xs:restriction base="xs:string">
            <!-- Admin places -->
            <xs:enumeration value="country" />
            <xs:enumeration value="region" />
            <xs:enumeration value="district_nomos" />
            <xs:enumeration value="city_village" />
            <xs:enumeration value="topos_ma" />
            <!-- Religios places -->
            <xs:enumeration value="monastery" />
            <xs:enumeration value="church_basilica" />
            <xs:enumeration value="episkopeion" />
            <xs:enumeration value="chapel" />
            <xs:enumeration value="oratory" />
            <xs:enumeration value="martyr_shrine" />
            <xs:enumeration value="temple" />
            <xs:enumeration value="hermitage" />
            <xs:enumeration value="tomb" />
            <!-- Natural fetures -->
            <xs:enumeration value="mount" />
            <xs:enumeration value="river" />
            <xs:enumeration value="lake" />
            <xs:enumeration value="harbour" />
            <!-- Lit -->
            <xs:enumeration value="biblical" />
          </xs:restriction>
        </xs:simpleType>
      </xs:attribute>
    </xs:complexType>
  </xs:element>

  <xs:element name="roleName">
    <xs:complexType mixed="true">
      <xs:choice minOccurs="0" maxOccurs="unbounded">
        <xs:element ref="ns1:lb"/>
      </xs:choice>
      <xs:attribute name="ref" use="optional" />
      <xs:attribute name="type" use="required">
        <xs:simpleType>
          <xs:restriction base="xs:string">
            <xs:enumeration value="religious" />
            <xs:enumeration value="ecclesiastical" />
            <xs:enumeration value="civil" />
            <xs:enumeration value="military" />
          </xs:restriction>
        </xs:simpleType>
      </xs:attribute>
    </xs:complexType>
  </xs:element>

  <xs:element name="org">
    <xs:complexType mixed="true">
      <xs:choice minOccurs="0" maxOccurs="unbounded">
        <xs:element ref="ns1:lb"/>
      </xs:choice>
      <xs:attribute name="ref" use="optional" />
      <xs:attribute name="type" use="required">
        <xs:simpleType>
          <xs:restriction base="xs:string">
            <xs:enumeration value="religious" />
            <xs:enumeration value="ethnic" />
          </xs:restriction>
        </xs:simpleType>
      </xs:attribute>
    </xs:complexType>
  </xs:element>

  <xs:element name="quote">
    <xs:complexType mixed="true">
      <xs:choice minOccurs="0" maxOccurs="unbounded">
      	<xs:element ref="ns1:date"/>
        <xs:element ref="ns1:gap"/>
        <xs:element ref="ns1:lb"/>
        <xs:element ref="ns1:persName"/>
        <xs:element ref="ns1:placeName"/>
        <xs:element ref="ns1:roleName"/>
        <xs:element ref="ns1:org"/>
        <xs:element ref="ns1:rs"/>
      </xs:choice>
      <xs:attribute name="ref" use="optional" />
      <xs:attribute name="type" use="required">
        <xs:simpleType>
          <xs:restriction base="xs:string">
            <xs:enumeration value="biblical" />
            <xs:enumeration value="classical" />
          </xs:restriction>
        </xs:simpleType>
      </xs:attribute>
    </xs:complexType>
  </xs:element>

  <xs:element name="rs">
    <xs:complexType mixed="true">
      <xs:choice minOccurs="0" maxOccurs="unbounded">
        <xs:element ref="ns1:lb"/>
      </xs:choice>
      <xs:attribute name="ref" use="optional" />
      <xs:attribute name="type" use="required">
        <xs:simpleType>
          <xs:restriction base="xs:string">
            <xs:enumeration value="object" />
            <xs:enumeration value="furniture" />
            <xs:enumeration value="service" />
          </xs:restriction>
        </xs:simpleType>
      </xs:attribute>
    </xs:complexType>
  </xs:element>

</xs:schema>

=== paths-erc/coptic-texts/colophons/paths.colophons.232.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-model href="http://www.tei-c.org/release/xml/tei/custom/schema/relaxng/tei_ms.rng" type="application/xml"
schematypens="http://purl.oclc.org/dsdl/schematron"?>
<TEI xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="http://www.tei-c.org/ns/1.0 ../paths-schema.xsd"
  xmlns="http://www.tei-c.org/ns/1.0">
  <teiHeader>
    <fileDesc>
      <titleStmt>
        <title>paths.colophons 197</title>
      </titleStmt>
      <publicationStmt>
        <p>paths.colophons 197</p>
      </publicationStmt>
      <sourceDesc>
        <p>paths.colophons.197</p>
      </sourceDesc>
    </fileDesc>
  </teiHeader>
  <text>
    <body>
      <p>
        ϣ̣[ⲗⲏⲗ ⲉϫ]ⲱ̣ⲓ ⲉⲛⲛⲁ̣ⲕⲁ⸱ⲡⲓ ϩⲉⲃⲓ⸱ⲉϩⲣⲁⲓ⸱ⲉⲛⲉⲧⲉϭⲓϫ⸱ⲉⲧⲧⲟⲩ|ⲁⲁ[ⲃ ϩ]ⲁ̣ⲡ︦ϭ︦ⲥ︦⸱ⲓⲁϯ⸱ⲉⲧⲧⲁ⸱ⲓⲏⲩ⸱ⲉⲧⲛⲁ⸱ⲱϣ⸱ϩⲉⲡⲓϫⲱⲙⲉ | ⲉⲧⲉⲡ̣ⲛⲟⲩⲧⲉ⸱ⲕⲁⲛⲁ⸱ⲉⲃⲁⲗ⸱ⲉⲛⲁ⸱ⲛⲁ⸱ⲃⲓ⸱ⲁⲛⲁ⸱ⲕⲡⲉ|(30)<persName type="copyist">ⲙⲁⲕⲁ⸱ⲣⲓ</persName>⸱ⲡⲓ⸱ⲁⲧⲉⲡϣⲁ⸱ⲡ[ⲣ]ⲁ̣ⲛ ⲧⲁⲩ⸱ⲧⲁ⸱ⲗⲁⲃ⸱ϩⲓ | ϩⲓϫⲱⲓ ϫⲉ<roleName type="ecclesiastical">ⲇⲓ(ⲁⲕⲱⲛ)</roleName> ⲡϣⲏⲛⲡⲙⲁ⸱ⲕ[ⲁⲣⲓ]ⲱⲥ | <roleName type="ecclesiastical">ⲡⲣ(ⲉ)ⲥ(ⲃⲩⲧⲉⲣⲟⲥ)</roleName> <persName type="monk">ⲓⲱ(ϩⲁⲛⲛⲏⲥ)</persName>
      </p>
    </body>
  </text>
</TEI>

=== paths-erc/coptic-texts/colophons/paths.colophons.68.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-model href="http://www.tei-c.org/release/xml/tei/custom/schema/relaxng/tei_ms.rng" type="application/xml"
schematypens="http://purl.oclc.org/dsdl/schematron"?>
<TEI xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="http://www.tei-c.org/ns/1.0 ../paths-schema.xsd"
  xmlns="http://www.tei-c.org/ns/1.0">
  <teiHeader>
    <fileDesc>
      <titleStmt>
        <title>paths.colophons.68</title>
      </titleStmt>
      <publicationStmt>
        <p>paths.colophons.68</p>
      </publicationStmt>
      <sourceDesc>
        <p>paths.colophons.68</p>
      </sourceDesc>
    </fileDesc>
  </teiHeader>
  <text>
    <body>
      <p>
ⲡⲁⲓⲡⲉ ⲡⲉⲣⲏⲧ ⲁⲩⲱ ⲡⲇⲱⲣⲟⲛ | ⲉⲛⲁⲡⲉⲣⲁⲧⲟⲛ ⲛⲧⲁⲙⲁⲓⲛⲟⲩ|ⲧⲉ ⲛⲥⲱⲛⲉ <persName type="donor">ⲕⲟⲩⲛⲧⲓⲧⲉ ⲧϣⲉ|ⲉⲣⲉ ⲙⲡⲙⲁⲕⲁⲣⲓⲟⲥ rasura</persName> |(5) ϩⲛⲧⲡⲟⲗⲓⲥ <placeName type="city_village" ref="paths:places:70">ⲣⲙⲟⲛ︤̄ⲧ︥</placeName>⸱ⲁⲥϥⲓⲡⲉϥ|ⲣⲟⲟⲩϣ ϩⲛⲛⲉⲥϩⲓⲥⲉ ⲙⲙⲓⲛ ⲉ|ⲙⲙⲟⲥ ⲁⲥⲧⲁⲁϥ ⲉϩⲟⲩⲛ ⲉⲡⲧⲟ|⟦ⲡⲧⲟ⟧ⲡⲟⲥ ⲙ<placeName type="monastery" ref="paths:places:000">ⲡⲁⲣⲭⲁⲅⲅⲉⲗⲟⲥ ⲙⲓ|ⲭⲁⲏⲗ</placeName> ⲙⲡ[   ] ϩⲁⲡⲟⲩ|(10)ϫⲁⲓ ⲛⲧⲉⲥⲯⲩⲭⲏ ⲙⲛⲧⲁⲡⲉⲥ|ϩⲁⲓ ⲙⲛⲧⲁⲛⲉⲥϣⲏⲣⲉ ϫⲉ|ⲕⲁⲥ ⲉⲣⲉⲡ<persName type="arch_angel">ⲁⲣⲭⲁⲅⲅⲉⲗⲟⲥ ⲙⲓⲭⲁ|ⲏ︤ⲗ︥</persName> ⲛⲁⲥⲙⲟⲩ ⲉⲣⲟⲥ ⲙⲛⲡⲉⲥϩⲁⲓ | ⲙ︤ⲛ︥ⲛⲉⲥϣⲏⲣⲉ · ⲛⲑⲉ ⲛ̄ⲧⲁϥ|(15)	ⲥⲙⲟⲩ ⲉⲛⲉⲛⲉⲓⲟⲧⲉ ⲙ̄ⲡⲡⲁⲧⲣⲓ|ⲁⲣⲭⲏⲥ · <persName type="biblical">ⲁⲃⲣⲁϩⲁⲙ</persName> · ⲙⲛ<persName type="biblical">ⲓⲉⲥⲁⲕ</persName> | ⲙⲛ<persName type="biblical">ⲓⲁⲕⲱⲃ</persName> · ⲙ︤ⲛ︥<persName type="biblical">ⲥⲁⲣⲣⲁ</persName> ⲙⲛ|<persName type="biblical">ϩⲉⲣⲉⲕⲕⲁ</persName> ·ⲙⲛ<persName type="biblical">ⲗⲓⲁ</persName> ⲙⲛ<persName type="biblical">ϩⲣⲁⲭⲏⲗ</persName> | ⲁⲩⲱ ⲉⲩϣⲁⲛⲉⲓ ⲉⲃⲟⲗ ϩⲙⲡⲉⲓ|(20)ⲃⲓⲟⲥ ⲛ̄ⲧⲉⲡ<persName type="arch_angel">ⲁⲣⲭⲁⲅⲅⲉⲗⲟⲥ | ⲉⲧⲟⲩⲁⲁⲃ ⲙⲓⲭⲁⲏⲗ</persName> ϫⲓϩⲙⲟⲧ | ⲉϩⲣⲁⲓ ⲉϫⲱⲟⲩ ⲛϥⲧⲟⲩϫⲟⲟⲩ | ⲉⲛⲕⲟⲗⲁⲥⲓⲥ ⲉⲧϩⲁϩⲟⲧⲉ ⲛϥ︦|ϫⲓⲧⲟⲩ ⲉϩⲟⲩⲛ ⲙⲙⲁ ⲛⲙⲧⲟⲛ |(25)	ⲛⲧⲙⲛⲧⲉⲣⲟ︥︥ ⲛⲙ̄ⲡⲏⲩⲉ̄ ⲛϥ|ⲧⲙⲙⲟⲟⲩ ⲉⲃⲟⲗ ϩⲙⲡϣⲏⲛ ⲙ̄|ⲡⲱ︦ⲛ︦ϩ︥ · ⲛϥⲁⲁⲩ ⲛⲙⲡϣⲁ | ⲛⲥⲱⲧⲙ ⲉⲧⲉⲥⲙⲏ ⲙⲙⲁⲕⲁⲣⲓ|ⲟⲛ ⲉⲧⲙⲉϩ ⲛⲣⲁϣⲉ ϩⲓⲉⲩⲫⲣⲟⲥⲩ|(30)ⲛⲏ ϫⲉ ⲁⲙⲏⲓⲧⲛ ⲛⲉⲧⲥⲙⲁⲙⲁⲁⲧ | ⲛⲧⲉⲡⲁⲉⲓⲱⲧ ⲛ̄ⲧⲉⲧⲛⲕⲗⲏ|ⲣⲟⲛⲟⲙⲉⲓ ⲛⲧⲙⲛⲧⲉⲣⲟ ⲛⲧⲁⲩ|ⲥⲃⲧⲱⲧⲥ ⲛⲏⲧⲛ ϫⲓⲛⲧⲕⲁ|ⲧⲁⲃⲟⲗⲏ ⲙⲡⲕⲟⲥⲙⲟⲥ ⸱ ⲁⲛⲟⲛ |(35) ⲙⲡⲅⲉⲛⲟⲥ ⲧⲏⲣϥ ⲛ̄ⲛⲉⲭⲣⲓⲥ|ϯⲁⲛⲟⲥ ⸱ ⲁⲙⲏⲛ (ⲕⲁⲓ) ⲁⲙⲏⲛ ⸱ ⲉϥⲉϣⲱⲡⲉ | ⲧⲉⲗⲓⲟⲩⲙⲛⲟⲩ ⸱ ⲙϣⲓⲣ ⲥⲟⲩⲏ̄ ⸺ ⲧⲟⲛ ⲁⲅⲓⲟⲛ ⲙⲁⲣⲧ(ⲩⲣⲟⲛ) ⲭ̄ϥ︤ⲑ︦ · ⲥⲁⲣⲁ|ⲕⲉⲛⲟⲥ ⲧ̄ⲟ̄ⲁ̄ ⲁⲛⲟⲕ ⲡⲉⲓⲉⲗⲁⲭ(ⲓⲥ)|(40)ⲧⲟⲥ <persName type="copyist">ⲙⲁⲣⲕⲟⲥ</persName> <roleName type="ecclesiastical">ⲇⲓ(ⲁ)ⲕ(ⲟⲛⲟⲥ)</roleName> ⲅⲣⲁⲯⲁⲥ | ϣⲗⲏⲗ ⲉϫⲱⲓ ⲛⲁⲅⲁⲡⲏ : -
    </p>
    </body>
  </text>
</TEI>

=== paths-erc/coptic-texts/colophons/paths.colophons.195.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-model href="http://www.tei-c.org/release/xml/tei/custom/schema/relaxng/tei_ms.rng" type="application/xml"
schematypens="http://purl.oclc.org/dsdl/schematron"?>
<TEI xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="http://www.tei-c.org/ns/1.0 ../paths-schema.xsd"
  xmlns="http://www.tei-c.org/ns/1.0">
  <teiHeader>
    <fileDesc>
      <titleStmt>
        <title>paths.colophons 195</title>
      </titleStmt>
      <publicationStmt>
        <p>paths.colophons 195</p>
      </publicationStmt>
      <sourceDesc>
        <p>paths.colophons.195</p>
      </sourceDesc>
    </fileDesc>
  </teiHeader>
  <text>
    <body>
      <p>
        ⲡ⳪︦ ⲁ̇ⲣⲓⲡⲓⲛⲁⲓ ⲛⲉⲙⲡⲉⲕⲃⲱⲕ ⲡⲓⲇ︦ⲓ︦ <persName type="copyist" ref="paths.persons.215">ⲅⲁⲃⲣⲓⲏⲗ</persName> ⲕⲟⲥⲙⲏⲧ ⲁⲙⲏⲛ
      </p>
    </body>
  </text>
</TEI>

=== paths-erc/coptic-texts/colophons/paths.colophons.222.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-model href="http://www.tei-c.org/release/xml/tei/custom/schema/relaxng/tei_ms.rng" type="application/xml"
schematypens="http://purl.oclc.org/dsdl/schematron"?>
<TEI xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="http://www.tei-c.org/ns/1.0 ../paths-schema.xsd"
  xmlns="http://www.tei-c.org/ns/1.0">
  <teiHeader>
    <fileDesc>
      <titleStmt>
        <title>paths.colophons 197</title>
      </titleStmt>
      <publicationStmt>
        <p>paths.colophons 197</p>
      </publicationStmt>
      <sourceDesc>
        <p>paths.colophons.197</p>
      </sourceDesc>
    </fileDesc>
  </teiHeader>
  <text>
    <body>
      <p>
        fol. 32v 
⳨ⲁⲣⲓⲡⲁⲙⲉⲩ ⲛⲁⲕⲁⲡⲓ ⲛⲁⲓⲁⲧⲉ ⲕⲗⲉⲣⲓⲕⲟⲥ ⲙⲉⲛⲉⲛ|ⲓⲁⲧⲉ ⲙⲟⲩⲛⲁːⲭⲟⲥ ⲉⲧⲛⲁⲙⲉⲗⲉ ϩⲉⲡⲓϫⲟⲙ ϣⲏⲗ | ⲉϫⲟⲓ ⲁⲛⲁⲕ ⲡⲓⲉⲃⲓⲉⲛ ⲡⲁⲣⲁⲡⲕⲁϩ ⲧⲉⲣⲃ ⲡⲇⲓⲁⲕⲟⲛⲟⲥ | ⲅⲱⲣⲅⲓ ⲡϣⲉⲣⲓ ⲛⲁⲛⲧⲣⲉⲥ ⲡⲁⲛⲁⲣⲙⲟⲩⲇⲓ⸫ | ⲡⲛⲟⲩⲧⲉ ⲁⲣⲓⲟⲩⲛⲁ ⲙⲉⲯⲓⲭⲏ ⲛⲉⲃⲓⲉⲛ ⲡⲉϩⲁⲩ | ⲡⲁϭⲓⲡϣⲓⲛⲓ ⲁⲓⲥϩⲉⲧⲛⲓⲥϩⲁⲓːⲭⲉ︦ⲭ ⲥⲟⲩⲓⲃ | ⲇⲓ̄ⲟ︦ⲕ︦ⲇⲓⲛ⸪ⲭⲓ̄︦ⲏ︦ ⲛⲉϩⲟⲩ ⲡⲁⲓⲟϯ ⲡⲇⲓⲁⲕⲟⲛⲟⲥ ϩⲓⲗⲉⲓ | ⲉⲃⲱ ⲛⲁⲣⲭⲉⲙⲁⲧⲣⲓⲧⲉⲥ ⲉⲧⲓⲉⲕⲗⲉⲥⲓⲁ S ⲡⲁⲡⲁ ⲥⲓⲥⲓⲛⲓ | ⲡⲉⲃϣⲉⲣⲓ S ⲡⲁⲡⲁ ⲡⲁⲩⲗⲉ ⲡⲟⲩⲁⲡⲟⲩⲁ ⲕⲁⲧⲁⲛⲉⲩⲣⲁⲛ
      </p>
    </body>
  </text>
</TEI>

=== paths-erc/coptic-texts/colophons/paths.colophons.178.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-model href="http://www.tei-c.org/release/xml/tei/custom/schema/relaxng/tei_ms.rng" type="application/xml"
schematypens="http://purl.oclc.org/dsdl/schematron"?>
<TEI xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="http://www.tei-c.org/ns/1.0 ../paths-schema.xsd"
  xmlns="http://www.tei-c.org/ns/1.0">
  <teiHeader>
    <fileDesc>
      <titleStmt>
        <title>paths.colophons.178</title>
      </titleStmt>
      <publicationStmt>
        <p>paths.colophons.178</p>
      </publicationStmt>
      <sourceDesc>
        <p>paths.colophons.178</p>
      </sourceDesc>
    </fileDesc>
  </teiHeader>
  <text>
    <body>
      <p>
⳧ ⲓⲥ ϯⲙⲉⲇⲁⲛⲓⲁ̇ ⲱ̇ ⲛⲁⲓⲟϯ ⲉⲑⲟⲩⲁⲃ ⲟⲩⲟⲛ ⲛⲓⲃⲉⲛ | ⲉⲧⲛⲁⲱϣ ϧⲉⲛⲡⲁⲓϫⲱⲙ ⲡⲁⲓ ⲛ̇ⲧⲉⲧⲉⲛⲉⲣ|ⲡⲙⲉⲩⲓ̇ ⲛ̇ⲡⲓⲣⲉϥⲉⲣⲛⲟⲃⲓ ⲡⲁⲣⲁⲣⲱⲙⲓ ⲛⲓⲃⲉⲛ | <persName type="civil" ref="paths.persons.202">ⲥⲉⲩⲏ̇ⲣⲟⲥ ⲩ(ⲓ)ⲟ(ⲥ) ⲭⲁⲑⲁⲣⲉⲛ</persName> ϩⲟⲡⲱⲥ ⲛ̇ⲧⲉⲡⲁ|ⲟ︦ⲥ︦ ⲓ︦ⲏ︦ⲥ︦ ⲡⲭ︦ⲥ︦ ϯⲙ̇ⲧⲟⲛ ⲛ̇ⲧⲉϥϫⲟⲃⲓ ⲛ̇ⲯⲩⲭ[ⲏ] | ϧⲉⲛⲧⲉϥⲙⲉⲧⲟⲩⲣⲟ ⲛ̇ⲉⲛⲉϩ ⲁ̇ⲙⲏⲛ ⲡⲏ ⲉⲧⲛⲁ|ϫⲟⲥ ϫⲉⲁ̇ⲙⲏⲛ ⲉ̇ϥⲉϭⲓ̇ ⲕⲁⲧⲁⲡⲓⲥⲙⲟⲩ ⲁⲙⲏⲛ (ⲟⲩⲟϩ) ⲁⲙⲏⲛ
    </p>
    </body>
  </text>
</TEI>

=== paths-erc/coptic-texts/colophons/paths.colophons.113.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-model href="http://www.tei-c.org/release/xml/tei/custom/schema/relaxng/tei_ms.rng" type="application/xml"
schematypens="http://purl.oclc.org/dsdl/schematron"?>
<TEI xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="http://www.tei-c.org/ns/1.0 ../paths-schema.xsd"
  xmlns="http://www.tei-c.org/ns/1.0">
  <teiHeader>
    <fileDesc>
      <titleStmt>
        <title>paths.colophons.113</title>
      </titleStmt>
      <publicationStmt>
        <p>paths.colophons.113</p>
      </publicationStmt>
      <sourceDesc>
        <p>paths.colophons.113</p>
      </sourceDesc>
    </fileDesc>
  </teiHeader>
  <text>
    <body>
      <p>
        ⲡϫⲟⲉⲓⲥ ⲓ(ⲏⲥⲟⲩ)ⲥ ⲡⲉⲭ(ⲣⲓⲥⲧⲟ)ⲥ | ⲥⲙⲟⲩ ⲁⲩⲱ ⲛⲉⲕϩⲁ|ⲣⲉϩ ⲉⲡⲱⲛⲉϩ ⲙ|ⲡⲉⲛⲙⲁⲓⲛⲟⲩⲧⲉ ⲛ|(5)ⲥ̣ⲟ̣ⲛ <persName type="donor" ref="paths.persons.209">ⲫⲓ̣ⲃ̣ⲁ̣ⲙⲱⲛ</persName>  | ⲡ̣[± 10] | [± 3]ϩ̣ⲛ̣[± 3] | [± 1]ⲓⲛ[± 2] ⲙ̣ⲙⲟϥ | ⲁϥϥⲓ̣[± 5]ⲙ|ⲡ[±3]ϫⲱⲱⲙⲉ | ⲁϥⲥⲁϩ̣ϥ ⲁϥⲧⲁⲁϥ | ⲉϩⲟⲩⲛ ⲉⲡⲧ̣ⲟ̣ⲡⲟⲥ ⲛ|[±10] | [± 8] ⲉⲧ|(15)ϣⲟⲟⲡ̣ ϩⲙⲡⲙⲟⲛⲁ̣ⲥ̣ⲧ̣ⲏ̣|ⲣ̣ⲓ̣ⲟ̣ⲛ [ⲙⲡⲉ]ⲛ̣ⲉⲓⲱⲧ ⲁ|ⲡ̣ⲁ [± 7] ⲁ̣ⲩ̣ⲱ | [ ± 10] | ⲣ̣ⲟ̣ⲩ̣ⲛ̣[ⲁ] ⲛⲙⲙⲁ̣ϥ̣ ⲙ̣ⲡⲉϩⲟ̣ⲩ | (20) ⲙⲡⲉϥ[ϭ]ⲙ[ⲡϣⲓ]ⲛ̣ⲉ ϩⲁ|ⲙⲏⲛ | ⲉ̣ⲅ(ⲱ) <persName type="copyist" ref="paths.persons.210">ⲙⲁ̣ⲣⲕⲟⲥ̣</persName> [± 2] ⲅⲁⲗ|[ⲗⲓⲟ]ⲅⲣⲁⲫⲉ̣ⲩⲥ̣ | [ ± 10]ⲅⲉ | [ ± 12]
      </p>
    </body>
  </text>
</TEI>

=== paths-erc/coptic-texts/colophons/paths.colophons.188.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-model href="http://www.tei-c.org/release/xml/tei/custom/schema/relaxng/tei_ms.rng" type="application/xml"
schematypens="http://purl.oclc.org/dsdl/schematron"?>
<TEI xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="http://www.tei-c.org/ns/1.0 ../paths-schema.xsd"
  xmlns="http://www.tei-c.org/ns/1.0">
  <teiHeader>
    <fileDesc>
      <titleStmt>
        <title>paths.colophons.188</title>
      </titleStmt>
      <publicationStmt>
        <p>paths.colophons.188</p>
      </publicationStmt>
      <sourceDesc>
        <p>paths.colophons.188</p>
      </sourceDesc>
    </fileDesc>
  </teiHeader>
  <text>
    <body>
      <p>
ⲡ⳪︦ ϯⲡⲓⲕⲁϯ ⲛ̇ⲛⲉⲛⲓⲟϯ ⲛ̇ⲣⲉϥⲱϣ ⲡⲓⲇ︦ⲓ︦ <persName type="ecclesiastical" ref="paths.persons.205">ⲥⲁⲣⲁⲡⲓⲱⲛ</persName> | ⲛⲉⲙⲡⲓⲇ︦ⲓ︦ <persName type="ecclesiastical" ref="paths.persons.206">ⲙⲏⲛⲁ</persName> ⲁⲙⲏⲛ
      </p>
    </body>
  </text>
</TEI>

=== paths-erc/coptic-texts/colophons/paths.colophons.260.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-model href="http://www.tei-c.org/release/xml/tei/custom/schema/relaxng/tei_ms.rng" type="application/xml"
schematypens="http://purl.oclc.org/dsdl/schematron"?>
<TEI xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="http://www.tei-c.org/ns/1.0 ../paths-schema.xsd"
  xmlns="http://www.tei-c.org/ns/1.0">
  <teiHeader>
    <fileDesc>
      <titleStmt>
        <title>paths.colophons 197</title>
      </titleStmt>
      <publicationStmt>
        <p>paths.colophons 197</p>
      </publicationStmt>
      <sourceDesc>
        <p>paths.colophons.197</p>
      </sourceDesc>
    </fileDesc>
  </teiHeader>
  <text>
    <body>
      <p>
        ⲫϯ ⲡⲓⲁⲅⲁⲑⲟⲥ ⲁⲣⲓⲟⲩⲛⲁⲓ ⲛⲉⲙⲡⲉⲕⲃ⸌ⲱ⸍ⲕ | ⲛ̇ⲣⲉϥⲉⲣⲛⲟⲃⲓ ⲉⲧⲁϥⲥϩⲁⲓ ⲅⲁⲃⲣⲓⲏⲗ | ⲟⲩⲟϩ ⲭⲱ ⲛⲏⲓ ⲉ̇ⲃⲟⲗ ⲱ̇ ⲡⲓⲛⲁⲏⲧ | ϫⲉⲇⲱⲣⲉⲁ̇ ⲛⲓⲃⲉⲛ ⲉⲑⲛⲁⲛⲉⲩ ⲥⲉϯ ⲙ̇|ⲙⲱⲟⲩ ⲉ̇ⲃⲟⲗ ϩⲓⲧⲟⲧⲕ ⲭ︦ⲣ︦ ⲙ︦ⲣ︦ ⲣ︦ⲟ︦ⲁ︦
      </p>
    </body>
  </text>
</TEI>
